// COMMANDER — White. Coordination, turn manipulation, team buffs.
// See server/cards/index.js for the effect DSL reference.
module.exports = [
  // ---- Class Staples ----
  { id: 'cmd_rally', name: 'Rally', arch: null, set: 'Staples', rarity: 'starter', cost: 1, type: 'spell', text: 'Target creature gets +1/+1 this turn', play: [{ t: 'creature', buffA: 1, buffH: 1, dur: 'turn' }] },
  { id: 'cmd_regroup', name: 'Regroup', arch: null, set: 'Staples', rarity: 'starter', cost: 1, type: 'spell', text: 'Restore 2 player HP', play: [{ heal: 2 }] },
  { id: 'cmd_redirect', name: 'Redirect', arch: null, set: 'Staples', rarity: 'starter', cost: 1, type: 'reaction', text: 'Reaction: Change the target of an attack to a different creature', reaction: { on: 'attack' }, play: [{ redirectAttack: true }] },
  { id: 'cmd_inspire', name: 'Inspire', arch: null, set: 'Staples', rarity: 'starter', cost: 2, type: 'spell', text: 'Target ally draws a card', play: [{ t: 'player', draw: 1 }] },

  // ---- MARSHAL: Sergeant (Starter) ----
  { id: 'cmd_squire', name: 'Squire', arch: 'marshal', set: 'Sergeant', rarity: 'starter', cost: 1, type: 'creature', atk: 1, hp: 2, text: 'None' },
  { id: 'cmd_bannerman', name: 'Bannerman', arch: 'marshal', set: 'Sergeant', rarity: 'starter', cost: 2, type: 'creature', atk: 2, hp: 2, text: 'When played, up to 2 creatures get +1 attack', play: [{ t: 'friendly', n: 2, upTo: true, buffA: 1, dur: 'perm' }] },
  { id: 'cmd_battlecry', name: 'Battle Cry', arch: 'marshal', set: 'Sergeant', rarity: 'starter', cost: 1, type: 'spell', text: 'Up to 2 creatures get +1 attack this turn', play: [{ t: 'friendly', n: 2, upTo: true, buffA: 1, dur: 'turn' }] },
  { id: 'cmd_holdtheline', name: 'Hold the Line', arch: 'marshal', set: 'Sergeant', rarity: 'starter', cost: 1, type: 'spell', text: 'Up to 2 creatures get +1 health this turn', play: [{ t: 'friendly', n: 2, upTo: true, buffH: 1, dur: 'turn' }] },
  { id: 'cmd_banner', name: 'Banner', arch: 'marshal', set: 'Sergeant', rarity: 'starter', cost: 2, type: 'persistent', atk: 0, hp: 2, text: 'Persistent. Up to 2 creatures get +1 attack', play: [{ t: 'friendly', n: 2, upTo: true, buffA: 1, dur: 'perm' }] },
  { id: 'cmd_formation', name: 'Formation', arch: 'marshal', set: 'Sergeant', rarity: 'starter', cost: 2, type: 'spell', text: 'Up to 3 creatures get +1/+1 this turn', play: [{ t: 'friendly', n: 3, upTo: true, buffA: 1, buffH: 1, dur: 'turn' }] },
  { id: 'cmd_warhorn', name: 'War Horn', arch: 'marshal', set: 'Sergeant', rarity: 'starter', cost: 3, type: 'spell', text: 'All friendly creatures get +2 attack this turn', play: [{ t: 'allFriendly', buffA: 2, dur: 'turn' }] },

  // ---- MARSHAL: Vanguard (Uncommon) ----
  { id: 'cmd_chargeorder', name: 'Charge Order', arch: 'marshal', set: 'Vanguard', rarity: 'uncommon', cost: 3, type: 'spell', text: 'All friendly creatures get +1 attack this turn', play: [{ t: 'allFriendly', buffA: 1, dur: 'turn' }] },
  { id: 'cmd_forwardmarch', name: 'Forward March', arch: 'marshal', set: 'Vanguard', rarity: 'uncommon', cost: 3, type: 'spell', text: 'All friendly creatures that attacked this turn may attack again. They get -1 attack for the second attack', play: [{ extraAttack: { scope: 'attacked' } }, { t: 'allFriendly', buffA: -1, dur: 'turn', onlyAttacked: true }] },
  { id: 'cmd_vanguardbanner', name: 'Vanguard Banner', arch: 'marshal', set: 'Vanguard', rarity: 'uncommon', cost: 4, type: 'persistent', atk: 0, hp: 3, text: 'Persistent. All friendly creatures get +1 attack', aura: { a: 1, scope: 'friendly' } },
  { id: 'cmd_wardrums', name: 'War Drums', arch: 'marshal', set: 'Vanguard', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Target creature gains Haste this turn. One other friendly creature gets +1 attack this turn', play: [{ t: 'creature', kw: ['haste'], dur: 'turn' }, { t: 'friendly', buffA: 1, dur: 'turn' }] },
  { id: 'cmd_bloodfrenzy', name: 'Blood Frenzy', arch: 'marshal', set: 'Vanguard', rarity: 'uncommon', cost: 3, type: 'spell', text: 'All friendly creatures get +1 attack this turn. They take 1 damage at end of turn', play: [{ t: 'allFriendly', buffA: 1, dur: 'turn' }, { schedule: { when: 'endTurn', t: 'allFriendly', dmg: 1 } }] },
  { id: 'cmd_exploitweakness', name: 'Exploit Weakness', arch: 'marshal', set: 'Vanguard', rarity: 'uncommon', cost: 1, type: 'spell', text: 'Target creature gets +3 attack this turn when attacking a creature with lower health than it', play: [{ t: 'creature', buffA: 3, dur: 'turn', note: 'Only applies when attacking a creature with lower health' }] },
  { id: 'cmd_pressforward', name: 'Press Forward', arch: 'marshal', set: 'Vanguard', rarity: 'uncommon', cost: 4, type: 'spell', text: 'All friendly creatures gain Trample this turn', play: [{ t: 'allFriendly', kw: ['trample'], dur: 'turn' }] },
  { id: 'cmd_rallyingcharge', name: 'Rallying Charge', arch: 'marshal', set: 'Vanguard', rarity: 'uncommon', cost: 4, type: 'spell', text: 'All friendly creatures get +1/+1 this turn. Draw a card', play: [{ t: 'allFriendly', buffA: 1, buffH: 1, dur: 'turn' }, { draw: 1 }] },
  { id: 'cmd_vanguardcaptain', name: 'Vanguard Captain', arch: 'marshal', set: 'Vanguard', rarity: 'uncommon', cost: 3, type: 'creature', atk: 2, hp: 3, text: 'Other creatures get +1 attack when attacking', aura: { a: 1, scope: 'friendly', other: true, note: 'Bonus applies while attacking' } },
  { id: 'cmd_overwhelmingforce', name: 'Overwhelming Force', arch: 'marshal', set: 'Vanguard', rarity: 'uncommon', cost: 5, type: 'spell', text: 'All friendly creatures get +2 attack this turn', play: [{ t: 'allFriendly', buffA: 2, dur: 'turn' }] },

  // ---- MARSHAL: Centurion (Uncommon) ----
  { id: 'cmd_shieldwall', name: 'Shield Wall', arch: 'marshal', set: 'Centurion', rarity: 'uncommon', cost: 3, type: 'spell', text: 'All friendly creatures get +1 health this turn', play: [{ t: 'allFriendly', buffH: 1, dur: 'turn' }] },
  { id: 'cmd_defensiveformation', name: 'Defensive Formation', arch: 'marshal', set: 'Centurion', rarity: 'uncommon', cost: 3, type: 'spell', text: 'All friendly creatures gain Shield 1', play: [{ t: 'allFriendly', shieldC: 1 }] },
  { id: 'cmd_centurionbanner', name: 'Centurion Banner', arch: 'marshal', set: 'Centurion', rarity: 'uncommon', cost: 4, type: 'persistent', atk: 0, hp: 3, text: 'Persistent. All friendly creatures get +1 health', aura: { h: 1, scope: 'friendly' } },
  { id: 'cmd_braceforimpact', name: 'Brace for Impact', arch: 'marshal', set: 'Centurion', rarity: 'uncommon', cost: 2, type: 'reaction', text: 'Reaction: All friendly creatures take 1 less damage from the next source this turn', reaction: { on: 'any' }, play: [{ t: 'allFriendly', shieldC: 1, note: 'Represents 1 less damage from the next source' }] },
  { id: 'cmd_stalwartorder', name: 'Stalwart Order', arch: 'marshal', set: 'Centurion', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Target creature with Taunt gets +3/+3 this turn', play: [{ t: 'creature', filter: 'kw:taunt', buffA: 3, buffH: 3, dur: 'turn' }] },
  { id: 'cmd_fortify', name: 'Fortify', arch: 'marshal', set: 'Centurion', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Target creature gets +3 health this turn and gains Taunt', play: [{ t: 'creature', buffH: 3, kw: ['taunt'], dur: 'turn' }] },
  { id: 'cmd_phalanx', name: 'Phalanx', arch: 'marshal', set: 'Centurion', rarity: 'uncommon', cost: 4, type: 'spell', text: 'All friendly creatures gain Taunt and +1 health this turn', play: [{ t: 'allFriendly', kw: ['taunt'], buffH: 1, dur: 'turn' }] },
  { id: 'cmd_centurionguard', name: 'Centurion Guard', arch: 'marshal', set: 'Centurion', rarity: 'uncommon', cost: 3, type: 'creature', atk: 2, hp: 4, kw: ['taunt'], text: 'Taunt. Other creatures with Taunt get +1 health', aura: { h: 1, scope: 'kw:taunt', other: true } },
  { id: 'cmd_standfast', name: 'Stand Fast', arch: 'marshal', set: 'Centurion', rarity: 'uncommon', cost: 2, type: 'reaction', text: 'Reaction: When a friendly creature would take lethal damage, it survives with 1 health instead', reaction: { on: 'wouldDie' }, play: [{ survive: 1 }] },
  { id: 'cmd_unbreakableline', name: 'Unbreakable Line', arch: 'marshal', set: 'Centurion', rarity: 'uncommon', cost: 5, type: 'spell', text: 'All friendly creatures get +2 health and Shield 2 this turn', play: [{ t: 'allFriendly', buffH: 2, dur: 'turn', shieldC: 2 }] },

  // ---- MARSHAL: General (Rare) ----
  { id: 'cmd_inspiringpresence', name: 'Inspiring Presence', arch: 'marshal', set: 'General', rarity: 'rare', cost: 3, type: 'creature', atk: 3, hp: 4, text: 'All friendly creatures get +1/+1 while this is alive', aura: { a: 1, h: 1, scope: 'friendly', other: true } },
  { id: 'cmd_battlefieldpromotion', name: 'Battlefield Promotion', arch: 'marshal', set: 'General', rarity: 'rare', cost: 2, type: 'spell', text: 'Target creature gets +2/+2 permanently', play: [{ t: 'creature', buffA: 2, buffH: 2, dur: 'perm' }] },
  { id: 'cmd_grandbanner', name: 'Grand Banner', arch: 'marshal', set: 'General', rarity: 'rare', cost: 5, type: 'persistent', atk: 0, hp: 4, text: 'Persistent. All friendly creatures get +1/+1', aura: { a: 1, h: 1, scope: 'friendly' } },
  { id: 'cmd_veteransinstinct', name: "Veteran's Instinct", arch: 'marshal', set: 'General', rarity: 'rare', cost: 2, type: 'reaction', text: 'Reaction: When a friendly creature kills an enemy creature, it gets +1/+1 permanently', reaction: { on: 'kill' }, play: [{ t: 'reactionSubject', buffA: 1, buffH: 1, dur: 'perm' }] },
  { id: 'cmd_tacticalretreat', name: 'Tactical Retreat', arch: 'marshal', set: 'General', rarity: 'rare', cost: 3, type: 'spell', text: "Return up to 2 friendly creatures to their owners' hands. All remaining friendly creatures get +2/+2 this turn", play: [{ bounce: { t: 'friendly', n: 2, upTo: true } }, { t: 'allFriendly', buffA: 2, buffH: 2, dur: 'turn' }] },
  { id: 'cmd_commandersauthority', name: "Commander's Authority", arch: 'marshal', set: 'General', rarity: 'rare', cost: 4, type: 'spell', text: 'Choose one: All friendly creatures get +3 attack this turn, OR all friendly creatures get +3 health this turn', play: [{ choose: [{ label: '+3 attack', acts: [{ t: 'allFriendly', buffA: 3, dur: 'turn' }] }, { label: '+3 health', acts: [{ t: 'allFriendly', buffH: 3, dur: 'turn' }] }] }] },
  { id: 'cmd_decoratedhero', name: 'Decorated Hero', arch: 'marshal', set: 'General', rarity: 'rare', cost: 4, type: 'creature', atk: 3, hp: 3, text: 'Gets +1/+1 permanently each time another friendly creature dies', allyDeath: [{ t: 'self', buffA: 1, buffH: 1, dur: 'perm' }] },
  { id: 'cmd_mobilize', name: 'Mobilize', arch: 'marshal', set: 'General', rarity: 'rare', cost: 3, type: 'spell', text: 'All friendly creatures get +1/+1 this turn. Target player draws 2 cards', play: [{ t: 'allFriendly', buffA: 1, buffH: 1, dur: 'turn' }, { t: 'player', draw: 2 }] },
  { id: 'cmd_forcedmarch', name: 'Forced March', arch: 'marshal', set: 'General', rarity: 'rare', cost: 4, type: 'spell', text: 'All friendly creatures gain Haste and +1 attack this turn. They take 1 damage at end of turn', play: [{ t: 'allFriendly', kw: ['haste'], buffA: 1, dur: 'turn' }, { schedule: { when: 'endTurn', t: 'allFriendly', dmg: 1 } }] },
  { id: 'cmd_legendofthefield', name: 'Legend of the Field', arch: 'marshal', set: 'General', rarity: 'rare', cost: 6, type: 'persistent', atk: 0, hp: 5, text: 'Persistent. Whenever a friendly creature attacks and kills an enemy creature, all other friendly creatures get +1 attack permanently', allyKill: [{ t: 'allFriendly', buffA: 1, dur: 'perm', exceptSubject: true }] },

  // ---- MARSHAL: Master Chief (Legendary) ----
  { id: 'cmd_masterchief', name: 'Master Chief', arch: 'marshal', set: 'Master Chief', rarity: 'legendary', cost: 7, type: 'creature', atk: 4, hp: 6, text: 'All friendly creatures get +2/+2. When a friendly creature kills an enemy creature, all other friendly creatures get +1 attack this turn', aura: { a: 2, h: 2, scope: 'friendly', other: true }, allyKill: [{ t: 'allFriendly', buffA: 1, dur: 'turn', exceptSubject: true }] },
  { id: 'cmd_lastcharge', name: 'Last Charge', arch: 'marshal', set: 'Master Chief', rarity: 'legendary', cost: 6, type: 'spell', text: 'All friendly creatures get +3/+3 and gain Trample this turn. At end of turn, all friendly creatures take 3 damage', play: [{ t: 'allFriendly', buffA: 3, buffH: 3, kw: ['trample'], dur: 'turn' }, { schedule: { when: 'endTurn', t: 'allFriendly', dmg: 3 } }] },

  // ---- TACTICIAN: Skirmish (Starter) ----
  { id: 'cmd_scout', name: 'Scout', arch: 'tactician', set: 'Skirmish', rarity: 'starter', cost: 1, type: 'creature', atk: 1, hp: 1, text: "When played, look at top card of DM's deck", play: [{ peek: { deck: 'dm', n: 1 } }] },
  { id: 'cmd_sergeant', name: 'Sergeant', arch: 'tactician', set: 'Skirmish', rarity: 'starter', cost: 2, type: 'creature', atk: 2, hp: 2, text: 'When another creature attacks, +1 attack this turn', allyAttack: [{ t: 'self', buffA: 1, dur: 'turn' }] },
  { id: 'cmd_presstheattack', name: 'Press the Attack', arch: 'tactician', set: 'Skirmish', rarity: 'starter', cost: 1, type: 'spell', text: 'Target creature that attacked may attack again', play: [{ t: 'friendly', filter: 'attacked', extraAttack: { scope: 'target' } }] },
  { id: 'cmd_scoutahead', name: 'Scout Ahead', arch: 'tactician', set: 'Skirmish', rarity: 'starter', cost: 1, type: 'spell', text: 'Look at top 3 cards of any deck. Reorder them', play: [{ peek: { deck: 'any', n: 3, reorder: true } }] },
  { id: 'cmd_doubletime', name: 'Double Time', arch: 'tactician', set: 'Skirmish', rarity: 'starter', cost: 2, type: 'spell', text: 'Target player may play an additional card this turn', manual: true },
  { id: 'cmd_flank', name: 'Flank', arch: 'tactician', set: 'Skirmish', rarity: 'starter', cost: 2, type: 'spell', text: 'Target creature gets +2 attack and may attack again', play: [{ t: 'friendly', buffA: 2, dur: 'turn', extraAttack: { scope: 'target' } }] },
  { id: 'cmd_anticipate', name: 'Anticipate', arch: 'tactician', set: 'Skirmish', rarity: 'starter', cost: 2, type: 'spell', text: "Look at top 3 cards of DM's deck. Reorder them", play: [{ peek: { deck: 'dm', n: 3, reorder: true } }] },

  // ---- TACTICIAN: Blitzkrieg (Uncommon) ----
  { id: 'cmd_rapiddeployment', name: 'Rapid Deployment', arch: 'tactician', set: 'Blitzkrieg', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Target player may play an additional card this turn. That card costs 1 less', manual: true },
  { id: 'cmd_surpriseattack', name: 'Surprise Attack', arch: 'tactician', set: 'Blitzkrieg', rarity: 'uncommon', cost: 1, type: 'spell', text: 'Target creature that already attacked may attack again this turn', play: [{ t: 'friendly', filter: 'attacked', extraAttack: { scope: 'target' } }] },
  { id: 'cmd_scoutreport', name: 'Scout Report', arch: 'tactician', set: 'Blitzkrieg', rarity: 'uncommon', cost: 1, type: 'spell', text: 'Look at the top 3 cards of any deck. Reorder them. Draw a card', play: [{ peek: { deck: 'any', n: 3, reorder: true } }, { draw: 1 }] },
  { id: 'cmd_flankingmaneuver', name: 'Flanking Maneuver', arch: 'tactician', set: 'Blitzkrieg', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Target creature gets +2 attack and may attack again this turn', play: [{ t: 'friendly', buffA: 2, dur: 'turn', extraAttack: { scope: 'target' } }] },
  { id: 'cmd_lightningraid', name: 'Lightning Raid', arch: 'tactician', set: 'Blitzkrieg', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Up to 2 creatures that already attacked may attack again this turn', play: [{ t: 'friendly', filter: 'attacked', n: 2, upTo: true, extraAttack: { scope: 'target' } }] },
  { id: 'cmd_seizeinitiative', name: 'Seize Initiative', arch: 'tactician', set: 'Blitzkrieg', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Choose a player. That player takes an extra turn after this one. They draw no card on that turn', manual: true },
  { id: 'cmd_tacticaladvantage', name: 'Tactical Advantage', arch: 'tactician', set: 'Blitzkrieg', rarity: 'uncommon', cost: 1, type: 'spell', text: "Look at the DM's hand. Draw a card", play: [{ peek: { hand: 'dm' } }, { draw: 1 }] },
  { id: 'cmd_overrun', name: 'Overrun', arch: 'tactician', set: 'Blitzkrieg', rarity: 'uncommon', cost: 3, type: 'spell', text: 'All friendly creatures that killed a creature this turn may attack again', play: [{ extraAttack: { scope: 'killed' } }] },
  { id: 'cmd_coordinatedstrike', name: 'Coordinated Strike', arch: 'tactician', set: 'Blitzkrieg', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Choose 2 creatures. They both get +1 attack and may attack a single target together, combining their damage', play: [{ t: 'friendly', n: 2, buffA: 1, dur: 'turn' }], manualNote: 'Combined attack: resolve the joint attack manually' },
  { id: 'cmd_totalassault', name: 'Total Assault', arch: 'tactician', set: 'Blitzkrieg', rarity: 'uncommon', cost: 4, type: 'spell', text: 'All friendly creatures get +1 attack this turn. All friendly creatures may attack again this turn. They take 1 damage at end of turn', play: [{ t: 'allFriendly', buffA: 1, dur: 'turn' }, { extraAttack: { scope: 'all' } }, { schedule: { when: 'endTurn', t: 'allFriendly', dmg: 1 } }] },

  // ---- TACTICIAN: Thermopylae (Uncommon) ----
  { id: 'cmd_fallback', name: 'Fall Back', arch: 'tactician', set: 'Thermopylae', rarity: 'uncommon', cost: 1, type: 'spell', text: "Return target friendly creature to its owner's hand. Draw a card", play: [{ bounce: { t: 'friendly', n: 1 } }, { draw: 1 }] },
  { id: 'cmd_delaytactics', name: 'Delay Tactics', arch: 'tactician', set: 'Thermopylae', rarity: 'uncommon', cost: 2, type: 'reaction', text: "Reaction: The DM's next card played this turn costs 1 additional mana", reaction: { on: 'any' }, manual: true },
  { id: 'cmd_reconnaissance', name: 'Reconnaissance', arch: 'tactician', set: 'Thermopylae', rarity: 'uncommon', cost: 1, type: 'spell', text: "Look at the top 5 cards of the DM's deck. Put one on the bottom", play: [{ peek: { deck: 'dm', n: 5, bottom: 1 } }] },
  { id: 'cmd_bottleneck', name: 'Bottleneck', arch: 'tactician', set: 'Thermopylae', rarity: 'uncommon', cost: 3, type: 'persistent', atk: 0, hp: 3, text: 'Persistent. The DM may only attack with 2 creatures per turn', manualNote: 'DM honors the 2-attacker limit while this is on the board' },
  { id: 'cmd_feignedretreat', name: 'Feigned Retreat', arch: 'tactician', set: 'Thermopylae', rarity: 'uncommon', cost: 2, type: 'spell', text: "Return up to 2 friendly creatures to their owners' hands. Draw a card for each", play: [{ bounce: { t: 'friendly', n: 2, upTo: true, drawPer: 1 } }] },
  { id: 'cmd_calculatedrisk', name: 'Calculated Risk', arch: 'tactician', set: 'Thermopylae', rarity: 'uncommon', cost: 1, type: 'reaction', text: 'Reaction: When a friendly creature is attacked, look at the top card of your deck. If it costs 2 or less, play it for free', reaction: { on: 'attack' }, manual: true },
  { id: 'cmd_stallingaction', name: 'Stalling Action', arch: 'tactician', set: 'Thermopylae', rarity: 'uncommon', cost: 2, type: 'reaction', text: "Reaction: The DM's next creature played this turn costs 2 more", reaction: { on: 'any' }, manual: true },
  { id: 'cmd_prepareddefense', name: 'Prepared Defense', arch: 'tactician', set: 'Thermopylae', rarity: 'uncommon', cost: 2, type: 'spell', text: "Look at the DM's hand. All friendly creatures get +1 health this turn", play: [{ peek: { hand: 'dm' } }, { t: 'allFriendly', buffH: 1, dur: 'turn' }] },
  { id: 'cmd_strategicwithdrawal', name: 'Strategic Withdrawal', arch: 'tactician', set: 'Thermopylae', rarity: 'uncommon', cost: 3, type: 'spell', text: "Return all friendly creatures with 2 or less health to their owners' hands. Draw a card", play: [{ bounce: { t: 'allFriendly', hpMax: 2 } }, { draw: 1 }] },
  { id: 'cmd_laststand', name: 'Last Stand', arch: 'tactician', set: 'Thermopylae', rarity: 'uncommon', cost: 4, type: 'spell', text: 'Until your next turn, all friendly creatures gain "when this would die, deal damage equal to its attack to a random enemy creature"', manual: true },

  // ---- TACTICIAN: Art of War (Rare) ----
  { id: 'cmd_perfectinformation', name: 'Perfect Information', arch: 'tactician', set: 'Art of War', rarity: 'rare', cost: 3, type: 'spell', text: "Look at the DM's hand and the top 5 cards of their deck. Reorder those 5 cards", play: [{ peek: { hand: 'dm' } }, { peek: { deck: 'dm', n: 5, reorder: true } }] },
  { id: 'cmd_outmaneuver', name: 'Outmaneuver', arch: 'tactician', set: 'Art of War', rarity: 'rare', cost: 3, type: 'reaction', text: 'Reaction: When DM declares attacks, you choose the targets instead', reaction: { on: 'attack' }, manual: true },
  { id: 'cmd_masterplan', name: 'Master Plan', arch: 'tactician', set: 'Art of War', rarity: 'rare', cost: 4, type: 'spell', text: 'Each player draws 2 cards. Each player may play one card for free this turn', play: [{ t: 'allPlayers', draw: 2 }], manualNote: 'Each player may play one card for free this turn (DM adjusts mana as needed)' },
  { id: 'cmd_ambushprotocol', name: 'Ambush Protocol', arch: 'tactician', set: 'Art of War', rarity: 'rare', cost: 3, type: 'reaction', text: 'Reaction: When DM plays a creature, target friendly creature may immediately attack it', reaction: { on: 'creaturePlayed' }, manual: true },
  { id: 'cmd_doubleagent', name: 'Double Agent', arch: 'tactician', set: 'Art of War', rarity: 'rare', cost: 4, type: 'spell', text: "Look at the DM's hand. Choose a card. The DM cannot play that card for 2 turns", play: [{ peek: { hand: 'dm' } }], manualNote: 'DM marks the chosen card as locked for 2 turns' },
  { id: 'cmd_warroom', name: 'War Room', arch: 'tactician', set: 'Art of War', rarity: 'rare', cost: 5, type: 'persistent', atk: 0, hp: 3, text: "Persistent. At start of each player's turn, that player looks at the top card of their deck and may put it on the bottom", startTurn: [{ peek: { deck: 'self', n: 1, bottom: 1, optional: true } }] },
  { id: 'cmd_pincermovement', name: 'Pincer Movement', arch: 'tactician', set: 'Art of War', rarity: 'rare', cost: 4, type: 'spell', text: 'Choose 2 creatures. They both may attack the same target. If that target dies, both may attack again', manual: true },
  { id: 'cmd_calculatedgambit', name: 'Calculated Gambit', arch: 'tactician', set: 'Art of War', rarity: 'rare', cost: 3, type: 'spell', text: 'Discard 2 cards. Draw 3 cards. Target player may play an additional card this turn', cost2: { discard: 2 }, play: [{ draw: 3 }] },
  { id: 'cmd_deconstructstrategy', name: 'Deconstruct Strategy', arch: 'tactician', set: 'Art of War', rarity: 'rare', cost: 3, type: 'reaction', text: "Reaction: Look at the top 3 cards of DM's deck. Exile one. Return the rest in any order", reaction: { on: 'any' }, play: [{ peek: { deck: 'dm', n: 3, exile: 1, reorder: true } }] },
  { id: 'cmd_supremetactician', name: 'Supreme Tactician', arch: 'tactician', set: 'Art of War', rarity: 'rare', cost: 5, type: 'creature', atk: 3, hp: 4, text: "At start of each round, look at the top card of the DM's deck. You may choose to put it on the bottom", startTurn: [{ peek: { deck: 'dm', n: 1, bottom: 1, optional: true } }] },

  // ---- TACTICIAN: Heaven and Earth (Legendary) ----
  { id: 'cmd_heaven', name: 'Heaven', arch: 'tactician', set: 'Heaven and Earth', rarity: 'legendary', cost: 7, type: 'spell', text: "Look at the top 10 cards of the DM's deck. Reorder them. Each player draws 2 cards and may play one card for free this turn", play: [{ peek: { deck: 'dm', n: 10, reorder: true } }, { t: 'allPlayers', draw: 2 }], manualNote: 'Each player may play one card for free this turn' },
  { id: 'cmd_earth', name: 'Earth', arch: 'tactician', set: 'Heaven and Earth', rarity: 'legendary', cost: 6, type: 'reaction', text: "Reaction: Until your next turn, you choose all targets for the DM's attacks and spells. The DM still chooses which cards to play", reaction: { on: 'any' }, manual: true },

  // ---- WARDEN: Fortress (Starter) ----
  { id: 'cmd_buckler', name: 'Buckler', arch: 'warden', set: 'Fortress', rarity: 'starter', cost: 1, type: 'spell', text: 'Give target creature +3 shield', play: [{ t: 'creature', shieldC: 3 }] },
  { id: 'cmd_mend', name: 'Mend', arch: 'warden', set: 'Fortress', rarity: 'starter', cost: 1, type: 'spell', text: 'Restore 3 player HP', play: [{ heal: 3 }] },
  { id: 'cmd_healingtower', name: 'Healing Tower', arch: 'warden', set: 'Fortress', rarity: 'starter', cost: 1, type: 'tower', atk: 0, hp: 1, text: 'Tower. Restore 1 player HP at start of turn', startTurn: [{ heal: 1 }] },
  { id: 'cmd_barrier', name: 'Barrier', arch: 'warden', set: 'Fortress', rarity: 'starter', cost: 2, type: 'spell', text: 'Create 5 player shield', play: [{ shield: 5 }] },
  { id: 'cmd_shieldtower', name: 'Shield Tower', arch: 'warden', set: 'Fortress', rarity: 'starter', cost: 2, type: 'tower', atk: 0, hp: 2, text: 'Tower. Generate 1 player shield at start of turn', startTurn: [{ shield: 1 }] },
  { id: 'cmd_restoration', name: 'Restoration', arch: 'warden', set: 'Fortress', rarity: 'starter', cost: 2, type: 'spell', text: 'Restore 5 player HP', play: [{ heal: 5 }] },
  { id: 'cmd_bastion', name: 'Bastion', arch: 'warden', set: 'Fortress', rarity: 'starter', cost: 3, type: 'tower', atk: 0, hp: 4, text: 'Tower. When friendly creature would die, destroy this instead', guard: 'die' },

  // ---- WARDEN: Rampart (Uncommon) ----
  { id: 'cmd_arrowtower', name: 'Arrow Tower', arch: 'warden', set: 'Rampart', rarity: 'uncommon', cost: 2, type: 'tower', atk: 0, hp: 3, text: 'Tower. Deal 1 damage to a random enemy creature at start of your turn', startTurn: [{ t: 'randomEnemy', dmg: 1 }] },
  { id: 'cmd_firetower', name: 'Fire Tower', arch: 'warden', set: 'Rampart', rarity: 'uncommon', cost: 3, type: 'tower', atk: 0, hp: 3, text: 'Tower. Deal 2 damage to target enemy creature at start of your turn', startTurn: [{ t: 'enemy', dmg: 2 }] },
  { id: 'cmd_spiketrap', name: 'Spike Trap', arch: 'warden', set: 'Rampart', rarity: 'uncommon', cost: 1, type: 'tower', atk: 0, hp: 1, text: 'Tower. When an enemy creature attacks, deal 1 damage to it', enemyAttack: [{ t: 'attacker', dmg: 1 }] },
  { id: 'cmd_ballistatower', name: 'Ballista Tower', arch: 'warden', set: 'Rampart', rarity: 'uncommon', cost: 4, type: 'tower', atk: 0, hp: 4, text: 'Tower. Deal 3 damage to target enemy creature at start of your turn', startTurn: [{ t: 'enemy', dmg: 3 }] },
  { id: 'cmd_catapult', name: 'Catapult', arch: 'warden', set: 'Rampart', rarity: 'uncommon', cost: 3, type: 'tower', atk: 0, hp: 3, text: 'Tower. Deal 1 damage to all enemy creatures at start of your turn', startTurn: [{ t: 'allEnemy', dmg: 1 }] },
  { id: 'cmd_thornwall', name: 'Thornwall', arch: 'warden', set: 'Rampart', rarity: 'uncommon', cost: 2, type: 'tower', atk: 0, hp: 3, text: 'Tower. When an enemy creature attacks any target, deal 1 damage to it', enemyAttack: [{ t: 'attacker', dmg: 1 }] },
  { id: 'cmd_warbeacon', name: 'War Beacon', arch: 'warden', set: 'Rampart', rarity: 'uncommon', cost: 3, type: 'tower', atk: 0, hp: 2, text: 'Tower. All friendly creatures get +1 attack', aura: { a: 1, scope: 'friendly' } },
  { id: 'cmd_bladebarrier', name: 'Blade Barrier', arch: 'warden', set: 'Rampart', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Create a 0/2 Tower token. When an enemy creature attacks, deal 2 damage to it. Destroy this tower at end of your next turn', play: [{ token: { name: 'Blade Barrier', a: 0, h: 2, n: 1, type: 'tower', retaliateOnEnemyAttack: 2, tempTurns: 2 } }] },
  { id: 'cmd_siegeplatform', name: 'Siege Platform', arch: 'warden', set: 'Rampart', rarity: 'uncommon', cost: 4, type: 'tower', atk: 0, hp: 4, text: 'Tower. Target friendly creature gets +2 attack at start of your turn', startTurn: [{ t: 'friendly', buffA: 2, dur: 'turn' }] },
  { id: 'cmd_fortifiedcannon', name: 'Fortified Cannon', arch: 'warden', set: 'Rampart', rarity: 'uncommon', cost: 5, type: 'tower', atk: 0, hp: 5, text: 'Tower. Deal 4 damage to target enemy creature at start of your turn', startTurn: [{ t: 'enemy', dmg: 4 }] },

  // ---- WARDEN: Citadel (Uncommon) ----
  { id: 'cmd_guardtower', name: 'Guard Tower', arch: 'warden', set: 'Citadel', rarity: 'uncommon', cost: 2, type: 'tower', atk: 0, hp: 3, text: 'Tower. Generate 1 player shield at start of your turn', startTurn: [{ shield: 1 }] },
  { id: 'cmd_sanctuary', name: 'Sanctuary', arch: 'warden', set: 'Citadel', rarity: 'uncommon', cost: 3, type: 'tower', atk: 0, hp: 4, text: 'Tower. Restore 2 player HP at start of your turn', startTurn: [{ heal: 2 }] },
  { id: 'cmd_reinforcedwall', name: 'Reinforced Wall', arch: 'warden', set: 'Citadel', rarity: 'uncommon', cost: 2, type: 'tower', atk: 0, hp: 5, kw: ['taunt'], text: 'Tower. Taunt' },
  { id: 'cmd_mendingshrine', name: 'Mending Shrine', arch: 'warden', set: 'Citadel', rarity: 'uncommon', cost: 3, type: 'tower', atk: 0, hp: 3, text: 'Tower. Restore 1 health to all friendly creatures at start of your turn', startTurn: [{ t: 'allFriendly', healC: 1 }] },
  { id: 'cmd_wardingobelisk', name: 'Warding Obelisk', arch: 'warden', set: 'Citadel', rarity: 'uncommon', cost: 3, type: 'tower', atk: 0, hp: 3, text: 'Tower. All friendly towers gain Shield 1 at start of your turn', startTurn: [{ t: 'friendlyTowers', shieldC: 1 }] },
  { id: 'cmd_haven', name: 'Haven', arch: 'warden', set: 'Citadel', rarity: 'uncommon', cost: 2, type: 'tower', atk: 0, hp: 3, text: 'Tower. Friendly creatures with 2 or less health cannot be targeted by spells', manualNote: 'Spell-protection aura: enforce when targeting' },
  { id: 'cmd_restorationfont', name: 'Restoration Font', arch: 'warden', set: 'Citadel', rarity: 'uncommon', cost: 4, type: 'tower', atk: 0, hp: 4, text: 'Tower. Restore 3 player HP at start of your turn', startTurn: [{ heal: 3 }] },
  { id: 'cmd_bulwark', name: 'Bulwark', arch: 'warden', set: 'Citadel', rarity: 'uncommon', cost: 3, type: 'spell', text: 'All friendly towers gain +3 health', play: [{ t: 'friendlyTowers', buffH: 3, dur: 'perm' }] },
  { id: 'cmd_aegisspire', name: 'Aegis Spire', arch: 'warden', set: 'Citadel', rarity: 'uncommon', cost: 4, type: 'tower', atk: 0, hp: 4, text: 'Tower. All friendly creatures gain Shield 1 at start of your turn', startTurn: [{ t: 'allFriendly', shieldC: 1 }] },
  { id: 'cmd_eternalbastion', name: 'Eternal Bastion', arch: 'warden', set: 'Citadel', rarity: 'uncommon', cost: 5, type: 'tower', atk: 0, hp: 6, text: 'Tower. When a friendly tower would be destroyed, restore it to full health instead. Can only trigger once per turn', manual: true },

  // ---- WARDEN: Keep (Rare) ----
  { id: 'cmd_grandhealingtower', name: 'Grand Healing Tower', arch: 'warden', set: 'Keep', rarity: 'rare', cost: 4, type: 'tower', atk: 0, hp: 5, text: 'Tower. Restore 3 player HP and 1 health to all friendly creatures at start of your turn', startTurn: [{ heal: 3 }, { t: 'allFriendly', healC: 1 }] },
  { id: 'cmd_shieldgenerator', name: 'Shield Generator', arch: 'warden', set: 'Keep', rarity: 'rare', cost: 4, type: 'tower', atk: 0, hp: 4, text: 'Tower. All friendly creatures and towers gain Shield 1 at start of your turn. You may only control one Shield Generator', startTurn: [{ t: 'allFriendly', shieldC: 1 }, { t: 'friendlyTowers', shieldC: 1 }] },
  { id: 'cmd_innersanctum', name: 'Inner Sanctum', arch: 'warden', set: 'Keep', rarity: 'rare', cost: 5, type: 'tower', atk: 0, hp: 3, text: 'Tower. Friendly creatures cannot take more than 3 damage from a single source', manualNote: 'Damage cap 3 per source while this is alive' },
  { id: 'cmd_reconstruct', name: 'Reconstruct', arch: 'warden', set: 'Keep', rarity: 'rare', cost: 5, type: 'spell', text: 'Return target destroyed tower from the graveyard to the board with full health', play: [{ rez: { n: 1, typeFilter: 'tower' } }] },
  { id: 'cmd_garrison', name: 'Garrison', arch: 'warden', set: 'Keep', rarity: 'rare', cost: 3, type: 'tower', atk: 0, hp: 4, text: 'Tower. When a friendly creature would take lethal damage, this tower takes the damage instead', manual: true },
  { id: 'cmd_fortresswall', name: 'Fortress Wall', arch: 'warden', set: 'Keep', rarity: 'rare', cost: 3, type: 'tower', atk: 0, hp: 8, kw: ['taunt'], text: 'Tower. Taunt' },
  { id: 'cmd_rejuvenationwellspring', name: 'Rejuvenation Wellspring', arch: 'warden', set: 'Keep', rarity: 'rare', cost: 5, type: 'tower', atk: 0, hp: 4, text: 'Tower. At start of your turn, restore 4 health to target friendly creature', startTurn: [{ t: 'friendly', healC: 4 }] },
  { id: 'cmd_architectsvision', name: "Architect's Vision", arch: 'warden', set: 'Keep', rarity: 'rare', cost: 4, type: 'spell', text: 'All friendly towers gain +3 health. Draw a card', play: [{ t: 'friendlyTowers', buffH: 3, dur: 'perm' }, { draw: 1 }] },
  { id: 'cmd_sanctuarygate', name: 'Sanctuary Gate', arch: 'warden', set: 'Keep', rarity: 'rare', cost: 4, type: 'tower', atk: 0, hp: 5, text: "Tower. Reaction: When a friendly creature would die, return it to its owner's hand instead. Can trigger once per round", guard: 'bounce' },
  { id: 'cmd_unassailablekeep', name: 'Unassailable Keep', arch: 'warden', set: 'Keep', rarity: 'rare', cost: 7, type: 'tower', atk: 0, hp: 4, text: 'Tower. All friendly towers restore 2 health to themselves at start of your turn', startTurn: [{ t: 'friendlyTowers', healC: 2 }] },

  // ---- WARDEN: Theodosian (Legendary) ----
  { id: 'cmd_theodosianwall', name: 'Theodosian Wall', arch: 'warden', set: 'Theodosian', rarity: 'legendary', cost: 8, type: 'tower', atk: 0, hp: 12, kw: ['taunt'], text: 'Tower. Taunt. All damage to player HP is redirected to this tower instead. Restore 2 health to this tower at start of your turn', playerDamageRedirect: true, startTurn: [{ t: 'self', healC: 2 }] },
  { id: 'cmd_consecratedground', name: 'Consecrated Ground', arch: 'warden', set: 'Theodosian', rarity: 'legendary', cost: 7, type: 'spell', text: 'All friendly towers become indestructible until your next turn. Restore all friendly towers to full health', play: [{ t: 'friendlyTowers', healC: 99 }], manualNote: 'Towers are indestructible until your next turn' },
];
