// CRAFTER — Green. Equipment, mana ramp, artifacts.
module.exports = [
  // ---- Class Staples ----
  { id: 'cra_energyshard', name: 'Energy Shard', arch: null, set: 'Staples', rarity: 'starter', cost: 1, type: 'spell', text: 'Add 2 mana to pool', play: [{ mana: 2 }] },
  { id: 'cra_harvest', name: 'Harvest', arch: null, set: 'Staples', rarity: 'starter', cost: 2, type: 'spell', text: 'Add 4 mana to pool', play: [{ mana: 4 }] },
  { id: 'cra_minortrinket', name: 'Minor Trinket', arch: null, set: 'Staples', rarity: 'starter', cost: 1, type: 'equip', text: 'Equipment: +1 attack', equip: { a: 1 } },
  { id: 'cra_repair', name: 'Repair', arch: null, set: 'Staples', rarity: 'starter', cost: 1, type: 'spell', text: 'Restore 2 health to target creature', play: [{ t: 'creature', healC: 2 }] },

  // ---- BLACKSMITH: Apprentice (Starter) ----
  { id: 'cra_shortsword', name: 'Shortsword', arch: 'blacksmith', set: 'Apprentice', rarity: 'starter', cost: 1, type: 'equip', text: 'Equipment: +2 attack', equip: { a: 2 } },
  { id: 'cra_leatherarmor', name: 'Leather Armor', arch: 'blacksmith', set: 'Apprentice', rarity: 'starter', cost: 1, type: 'equip', text: 'Equipment: +2 health', equip: { h: 2 } },
  { id: 'cra_longsword', name: 'Longsword', arch: 'blacksmith', set: 'Apprentice', rarity: 'starter', cost: 2, type: 'equip', text: 'Equipment: +3 attack', equip: { a: 3 } },
  { id: 'cra_chainmail', name: 'Chainmail', arch: 'blacksmith', set: 'Apprentice', rarity: 'starter', cost: 2, type: 'equip', text: 'Equipment: +3 health', equip: { h: 3 } },
  { id: 'cra_spikedshield', name: 'Spiked Shield', arch: 'blacksmith', set: 'Apprentice', rarity: 'starter', cost: 3, type: 'equip', text: 'Equipment: +1 attack, +3 health', equip: { a: 1, h: 3 } },
  { id: 'cra_vampiricblade', name: 'Vampiric Blade', arch: 'blacksmith', set: 'Apprentice', rarity: 'starter', cost: 3, type: 'equip', text: 'Equipment: +2 attack. Damage dealt restores player HP', equip: { a: 2, kw: ['lifelink'] } },
  { id: 'cra_masterworkplate', name: 'Masterwork Plate', arch: 'blacksmith', set: 'Apprentice', rarity: 'starter', cost: 4, type: 'equip', text: 'Equipment: +2 attack, +4 health', equip: { a: 2, h: 4 } },

  // ---- BLACKSMITH: Tribal (Common) ----
  { id: 'cra_boneclub', name: 'Bone Club', arch: 'blacksmith', set: 'Tribal', rarity: 'common', cost: 1, type: 'equip', text: 'Equipment. +3 attack. Breaks after equipped creature attacks', equip: { a: 3, breaks: 'attack' } },
  { id: 'cra_hideshield', name: 'Hide Shield', arch: 'blacksmith', set: 'Tribal', rarity: 'common', cost: 1, type: 'equip', text: 'Equipment. +4 health. Breaks after equipped creature is attacked', equip: { h: 4, breaks: 'attacked' } },
  { id: 'cra_toothnecklace', name: 'Tooth Necklace', arch: 'blacksmith', set: 'Tribal', rarity: 'common', cost: 1, type: 'equip', text: 'Equipment. +2 attack. Equipped creature gains Lifelink. Breaks after equipped creature attacks', equip: { a: 2, kw: ['lifelink'], breaks: 'attack' } },
  { id: 'cra_jawboneaxe', name: 'Jawbone Axe', arch: 'blacksmith', set: 'Tribal', rarity: 'common', cost: 2, type: 'equip', text: 'Equipment. +5 attack. Breaks after equipped creature attacks', equip: { a: 5, breaks: 'attack' } },
  { id: 'cra_skullhelm', name: 'Skull Helm', arch: 'blacksmith', set: 'Tribal', rarity: 'common', cost: 2, type: 'equip', text: 'Equipment. +3 health. Equipped creature gains Taunt. Breaks after equipped creature is attacked', equip: { h: 3, kw: ['taunt'], breaks: 'attacked' } },
  { id: 'cra_bonesplintarmor', name: 'Bonesplint Armor', arch: 'blacksmith', set: 'Tribal', rarity: 'common', cost: 2, type: 'equip', text: 'Equipment. +5 health. Breaks after equipped creature is attacked', equip: { h: 5, breaks: 'attacked' } },
  { id: 'cra_tuskspear', name: 'Tusk Spear', arch: 'blacksmith', set: 'Tribal', rarity: 'common', cost: 2, type: 'equip', text: 'Equipment. +3 attack. Equipped creature gains First Strike. Breaks after equipped creature attacks', equip: { a: 3, kw: ['firststrike'], breaks: 'attack' } },
  { id: 'cra_ritualmask', name: 'Ritual Mask', arch: 'blacksmith', set: 'Tribal', rarity: 'common', cost: 1, type: 'equip', text: 'Equipment. Equipped creature gains Deathtouch. Breaks after equipped creature attacks', equip: { kw: ['deathtouch'], breaks: 'attack' } },
  { id: 'cra_sinewbow', name: 'Sinew Bow', arch: 'blacksmith', set: 'Tribal', rarity: 'common', cost: 2, type: 'equip', text: 'Equipment. +2 attack. Equipped creature gains Trample. Breaks after equipped creature attacks', equip: { a: 2, kw: ['trample'], breaks: 'attack' } },
  { id: 'cra_warpaint', name: 'War Paint', arch: 'blacksmith', set: 'Tribal', rarity: 'common', cost: 1, type: 'equip', text: 'Equipment. +2 attack, +2 health. Breaks at end of your turn', equip: { a: 2, h: 2, breaks: 'endTurn' } },

  // ---- BLACKSMITH: Dwarven (Uncommon) ----
  { id: 'cra_dwarvenhammer', name: 'Dwarven Hammer', arch: 'blacksmith', set: 'Dwarven', rarity: 'uncommon', cost: 3, type: 'equip', text: 'Equipment. +4 attack', equip: { a: 4 } },
  { id: 'cra_dwarvenshield', name: 'Dwarven Shield', arch: 'blacksmith', set: 'Dwarven', rarity: 'uncommon', cost: 3, type: 'equip', text: 'Equipment. +4 health', equip: { h: 4 } },
  { id: 'cra_dwarvenhelm', name: 'Dwarven Helm', arch: 'blacksmith', set: 'Dwarven', rarity: 'uncommon', cost: 2, type: 'equip', text: 'Equipment. +2 health. Shield 2', equip: { h: 2, shield: 2 } },
  { id: 'cra_dwarvenbattleaxe', name: 'Dwarven Battleaxe', arch: 'blacksmith', set: 'Dwarven', rarity: 'uncommon', cost: 4, type: 'equip', text: 'Equipment. +5 attack', equip: { a: 5 } },
  { id: 'cra_dwarvenplate', name: 'Dwarven Plate', arch: 'blacksmith', set: 'Dwarven', rarity: 'uncommon', cost: 4, type: 'equip', text: 'Equipment. +3 health. Shield 3', equip: { h: 3, shield: 3 } },
  { id: 'cra_dwarvengreathammer', name: 'Dwarven Greathammer', arch: 'blacksmith', set: 'Dwarven', rarity: 'uncommon', cost: 5, type: 'equip', text: 'Equipment. +4 attack. Trample', equip: { a: 4, kw: ['trample'] } },
  { id: 'cra_dwarvenbulwark', name: 'Dwarven Bulwark', arch: 'blacksmith', set: 'Dwarven', rarity: 'uncommon', cost: 5, type: 'equip', text: 'Equipment. +5 health. Taunt', equip: { h: 5, kw: ['taunt'] } },
  { id: 'cra_masterforgedblade', name: 'Masterforged Blade', arch: 'blacksmith', set: 'Dwarven', rarity: 'uncommon', cost: 4, type: 'equip', text: 'Equipment. +3 attack. +1 attack for each other equipment you control', equip: { a: 3 }, manualNote: '+1 attack per other equipment (adjust manually)' },
  { id: 'cra_runeforgedarmor', name: 'Runeforged Armor', arch: 'blacksmith', set: 'Dwarven', rarity: 'uncommon', cost: 4, type: 'equip', text: 'Equipment. +3 health. Equipped creature cannot be targeted by spells', equip: { h: 3, kw: ['nospell'] } },
  { id: 'cra_anvilofthedeep', name: 'Anvil of the Deep', arch: 'blacksmith', set: 'Dwarven', rarity: 'uncommon', cost: 5, type: 'persistent', atk: 0, hp: 3, text: 'Persistent. All equipment you play costs 1 less mana', costMod: { type: 'equip', delta: -1 } },

  // ---- BLACKSMITH: Elven (Uncommon) ----
  { id: 'cra_elvenshortbow', name: 'Elven Shortbow', arch: 'blacksmith', set: 'Elven', rarity: 'uncommon', cost: 2, type: 'equip', text: 'Equipment. +1 attack. Equipped creature gains First Strike', equip: { a: 1, kw: ['firststrike'] } },
  { id: 'cra_elvencloak', name: 'Elven Cloak', arch: 'blacksmith', set: 'Elven', rarity: 'uncommon', cost: 2, type: 'equip', text: 'Equipment. +1 health. Equipped creature cannot be targeted by spells', equip: { h: 1, kw: ['nospell'] } },
  { id: 'cra_moonblade', name: 'Moonblade', arch: 'blacksmith', set: 'Elven', rarity: 'uncommon', cost: 3, type: 'equip', text: 'Equipment. +2 attack. Equipped creature gains Lifelink', equip: { a: 2, kw: ['lifelink'] } },
  { id: 'cra_sylvanarmor', name: 'Sylvan Armor', arch: 'blacksmith', set: 'Elven', rarity: 'uncommon', cost: 3, type: 'equip', text: 'Equipment. +1 health. Equipped creature gains "restore 1 health to itself at start of your turn"', equip: { h: 1, regen: 1 } },
  { id: 'cra_windrunnerboots', name: 'Windrunner Boots', arch: 'blacksmith', set: 'Elven', rarity: 'uncommon', cost: 2, type: 'equip', text: 'Equipment. Equipped creature gains Haste', equip: { kw: ['haste'] } },
  { id: 'cra_thornweave', name: 'Thornweave', arch: 'blacksmith', set: 'Elven', rarity: 'uncommon', cost: 2, type: 'equip', text: 'Equipment. +1 health. When equipped creature takes damage, deal 1 damage to attacker', equip: { h: 1, kw: ['retaliate:1'] } },
  { id: 'cra_starlightdagger', name: 'Starlight Dagger', arch: 'blacksmith', set: 'Elven', rarity: 'uncommon', cost: 3, type: 'equip', text: 'Equipment. +2 attack. Equipped creature gains Deathtouch', equip: { a: 2, kw: ['deathtouch'] } },
  { id: 'cra_featherguard', name: 'Featherguard', arch: 'blacksmith', set: 'Elven', rarity: 'uncommon', cost: 2, type: 'equip', text: 'Equipment. Shield 3', equip: { shield: 3 } },
  { id: 'cra_everwoodstaff', name: 'Everwood Staff', arch: 'blacksmith', set: 'Elven', rarity: 'uncommon', cost: 3, type: 'equip', text: 'Equipment. Equipped creature gains "add 1 mana at start of your turn"', equip: { manaGen: 1 } },
  { id: 'cra_spirittreebow', name: 'Spirit Tree Bow', arch: 'blacksmith', set: 'Elven', rarity: 'uncommon', cost: 4, type: 'equip', text: 'Equipment. +2 attack. First Strike. When equipped creature kills a creature, draw a card', equip: { a: 2, kw: ['firststrike'], onKillDraw: 1 } },

  // ---- BLACKSMITH: Daedra (Rare) ----
  { id: 'cra_daedricblade', name: 'Daedric Blade', arch: 'blacksmith', set: 'Daedra', rarity: 'rare', cost: 2, type: 'equip', text: 'Equipment. +5 attack. Equipped creature takes 1 damage at start of your turn', equip: { a: 5, selfDmg: 1 } },
  { id: 'cra_daedricplate', name: 'Daedric Plate', arch: 'blacksmith', set: 'Daedra', rarity: 'rare', cost: 2, type: 'equip', text: 'Equipment. +6 health. Lose 1 player HP at start of your turn', equip: { h: 6, hpDrain: 1 } },
  { id: 'cra_daedrichelm', name: 'Daedric Helm', arch: 'blacksmith', set: 'Daedra', rarity: 'rare', cost: 2, type: 'equip', text: "Equipment. +3 attack. Equipped creature gains Trample. Equipped creature can't be healed", equip: { a: 3, kw: ['trample'] }, manualNote: 'Equipped creature cannot be healed' },
  { id: 'cra_daedricgauntlets', name: 'Daedric Gauntlets', arch: 'blacksmith', set: 'Daedra', rarity: 'rare', cost: 3, type: 'equip', text: 'Equipment. +4 attack. Equipped creature gains Deathtouch. Lose 2 player HP when equipped', equip: { a: 4, kw: ['deathtouch'], onEquipLoseHP: 2 } },
  { id: 'cra_daedricgreatsword', name: 'Daedric Greatsword', arch: 'blacksmith', set: 'Daedra', rarity: 'rare', cost: 4, type: 'equip', text: 'Equipment. +7 attack. Equipped creature takes 2 damage at start of your turn', equip: { a: 7, selfDmg: 2 } },
  { id: 'cra_daedricshield', name: 'Daedric Shield', arch: 'blacksmith', set: 'Daedra', rarity: 'rare', cost: 3, type: 'equip', text: 'Equipment. +4 health. Shield 4. When shield breaks, deal 4 damage to player HP', equip: { h: 4, shield: 4 }, manualNote: 'When shield breaks, lose 4 player HP' },
  { id: 'cra_daedricboots', name: 'Daedric Boots', arch: 'blacksmith', set: 'Daedra', rarity: 'rare', cost: 2, type: 'equip', text: 'Equipment. Equipped creature gains Haste. Equipped creature gets -1 health permanently each turn', equip: { kw: ['haste'], selfDmg: 1 } },
  { id: 'cra_soulsnareamulet', name: 'Soulsnare Amulet', arch: 'blacksmith', set: 'Daedra', rarity: 'rare', cost: 3, type: 'equip', text: 'Equipment. When equipped creature kills a creature, draw 2 cards. When equipped creature dies, discard your hand', equip: { onKillDraw: 2 }, manualNote: 'When wearer dies, discard your hand' },
  { id: 'cra_hellforgedcrown', name: 'Hellforged Crown', arch: 'blacksmith', set: 'Daedra', rarity: 'rare', cost: 4, type: 'equip', text: 'Equipment. +3 attack. +3 health. All healing to player HP is halved while this is equipped', equip: { a: 3, h: 3 }, manualNote: 'Player HP healing halved while equipped' },
  { id: 'cra_daedricanvil', name: 'Daedric Anvil', arch: 'blacksmith', set: 'Daedra', rarity: 'rare', cost: 5, type: 'persistent', atk: 0, hp: 3, text: 'Persistent. All equipment you play gains +2 to its attack bonus. Lose 1 player HP each time you equip something', equipAuraBonus: { a: 2, loseHP: 1 } },

  // ---- BLACKSMITH: Angelic (Legendary) ----
  { id: 'cra_angelicarmament', name: 'Angelic Armament', arch: 'blacksmith', set: 'Angelic', rarity: 'legendary', cost: 6, type: 'equip', text: 'Equipment. +4 attack. +4 health. Equipped creature gains Lifelink and First Strike. When equipped creature kills a creature, restore 2 player HP', equip: { a: 4, h: 4, kw: ['lifelink', 'firststrike'], onKillHeal: 2 } },
  { id: 'cra_divineforge', name: 'Divine Forge', arch: 'blacksmith', set: 'Angelic', rarity: 'legendary', cost: 7, type: 'persistent', atk: 0, hp: 6, text: 'Persistent. At start of your turn, create a copy of a random equipment in your hand and equip it to a friendly creature for free', manual: true },

  // ---- FARMER: Farmland (Starter) ----
  { id: 'cra_sprout', name: 'Sprout', arch: 'farmer', set: 'Farmland', rarity: 'starter', cost: 1, type: 'creature', atk: 1, hp: 1, tribe: 'Plant', text: 'Add 1 mana at start of your turn', startTurn: [{ mana: 1 }] },
  { id: 'cra_cornstalk', name: 'Cornstalk', arch: 'farmer', set: 'Farmland', rarity: 'starter', cost: 1, type: 'creature', atk: 0, hp: 2, tribe: 'Plant', text: 'Add 1 mana at start of your turn', startTurn: [{ mana: 1 }] },
  { id: 'cra_thornbush', name: 'Thornbush', arch: 'farmer', set: 'Farmland', rarity: 'starter', cost: 2, type: 'creature', atk: 2, hp: 2, tribe: 'Plant', text: 'When this takes damage, add 1 mana', damaged: [{ mana: 1 }] },
  { id: 'cra_sunflower', name: 'Sunflower', arch: 'farmer', set: 'Farmland', rarity: 'starter', cost: 2, type: 'creature', atk: 0, hp: 3, tribe: 'Plant', text: 'Add 2 mana at start of your turn', startTurn: [{ mana: 2 }] },
  { id: 'cra_harvestgolem', name: 'Harvest Golem', arch: 'farmer', set: 'Farmland', rarity: 'starter', cost: 3, type: 'creature', atk: 2, hp: 3, tribe: 'Plant', text: '+1/+1 for every 5 mana in pool', scaling: { a: 1, h: 1, per: 'mana:5' } },
  { id: 'cra_ancientoak', name: 'Ancient Oak', arch: 'farmer', set: 'Farmland', rarity: 'starter', cost: 5, type: 'creature', atk: 3, hp: 5, tribe: 'Plant', text: 'Add 2 mana at start of turn. Other plants get +1 health', startTurn: [{ mana: 2 }], aura: { h: 1, scope: 'tribe:Plant', other: true } },

  // ---- FARMER: Desert (Common) ----
  { id: 'cra_smallcactus', name: 'Small Cactus', arch: 'farmer', set: 'Desert', rarity: 'common', cost: 1, type: 'creature', atk: 1, hp: 2, tribe: 'Plant', kw: ['retaliate:1'], text: 'When this takes damage, deal 1 damage to the attacker' },
  { id: 'cra_pricklypear', name: 'Prickly Pear', arch: 'farmer', set: 'Desert', rarity: 'common', cost: 1, type: 'creature', atk: 0, hp: 3, tribe: 'Plant', kw: ['retaliate:1'], text: 'When this takes damage, deal 1 damage to the attacker' },
  { id: 'cra_desertbloom', name: 'Desert Bloom', arch: 'farmer', set: 'Desert', rarity: 'common', cost: 1, type: 'creature', atk: 0, hp: 2, tribe: 'Plant', text: 'Add 1 mana at start of your turn', startTurn: [{ mana: 1 }] },
  { id: 'cra_tumbleweed', name: 'Tumbleweed', arch: 'farmer', set: 'Desert', rarity: 'common', cost: 1, type: 'creature', atk: 1, hp: 1, tribe: 'Plant', text: 'When this dies, add 2 mana', death: [{ mana: 2 }] },
  { id: 'cra_barrelcactus', name: 'Barrel Cactus', arch: 'farmer', set: 'Desert', rarity: 'common', cost: 2, type: 'creature', atk: 1, hp: 4, tribe: 'Plant', kw: ['retaliate:1'], text: 'When this takes damage, deal 1 damage to the attacker' },
  { id: 'cra_saguaro', name: 'Saguaro', arch: 'farmer', set: 'Desert', rarity: 'common', cost: 3, type: 'creature', atk: 2, hp: 5, tribe: 'Plant', kw: ['retaliate:2'], text: 'When this takes damage, deal 2 damage to the attacker' },
  { id: 'cra_oasisflower', name: 'Oasis Flower', arch: 'farmer', set: 'Desert', rarity: 'common', cost: 2, type: 'creature', atk: 0, hp: 3, tribe: 'Plant', text: 'Add 1 mana at start of your turn. Restore 1 player HP at start of your turn', startTurn: [{ mana: 1 }, { heal: 1 }] },
  { id: 'cra_aloeplant', name: 'Aloe Plant', arch: 'farmer', set: 'Desert', rarity: 'common', cost: 2, type: 'creature', atk: 0, hp: 3, tribe: 'Plant', text: 'Restore 2 health to target creature at start of your turn', startTurn: [{ t: 'friendly', healC: 2 }] },
  { id: 'cra_joshuatree', name: 'Joshua Tree', arch: 'farmer', set: 'Desert', rarity: 'common', cost: 3, type: 'creature', atk: 1, hp: 4, tribe: 'Plant', text: 'Add 1 mana at start of your turn. Other Desert plants get +1 health', startTurn: [{ mana: 1 }], aura: { h: 1, scope: 'tribe:Plant', other: true } },
  { id: 'cra_sandvine', name: 'Sand Vine', arch: 'farmer', set: 'Desert', rarity: 'common', cost: 2, type: 'creature', atk: 2, hp: 2, tribe: 'Plant', text: 'When played, target enemy creature gets -1 attack for 3 rounds', play: [{ t: 'enemy', buffA: -1, dur: 3 }] },

  // ---- FARMER: Jungle (Uncommon) ----
  { id: 'cra_junglefern', name: 'Jungle Fern', arch: 'farmer', set: 'Jungle', rarity: 'uncommon', cost: 1, type: 'creature', atk: 0, hp: 2, tribe: 'Plant', text: 'Add 1 mana at start of your turn', startTurn: [{ mana: 1 }] },
  { id: 'cra_vinecreeper', name: 'Vine Creeper', arch: 'farmer', set: 'Jungle', rarity: 'uncommon', cost: 2, type: 'creature', atk: 1, hp: 3, tribe: 'Plant', text: 'Add 1 mana at start of your turn. When this generates mana, gain +1 health', startTurn: [{ mana: 1 }, { t: 'self', buffH: 1, dur: 'perm' }] },
  { id: 'cra_pitcherplant', name: 'Pitcher Plant', arch: 'farmer', set: 'Jungle', rarity: 'uncommon', cost: 2, type: 'creature', atk: 1, hp: 3, tribe: 'Plant', text: 'When an enemy creature dies, add 1 mana', enemyDeath: [{ mana: 1 }] },
  { id: 'cra_kapoktree', name: 'Kapok Tree', arch: 'farmer', set: 'Jungle', rarity: 'uncommon', cost: 4, type: 'creature', atk: 2, hp: 6, tribe: 'Plant', text: 'Add 2 mana at start of your turn. Other Jungle plants get +1 health', startTurn: [{ mana: 2 }], aura: { h: 1, scope: 'tribe:Plant', other: true } },
  { id: 'cra_venusflytrap', name: 'Venus Flytrap', arch: 'farmer', set: 'Jungle', rarity: 'uncommon', cost: 3, type: 'creature', atk: 2, hp: 3, tribe: 'Plant', text: 'When an enemy creature with 2 or less attack deals damage to this, destroy that creature', manual: true },
  { id: 'cra_overgrowth', name: 'Overgrowth', arch: 'farmer', set: 'Jungle', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Add 1 mana for each plant creature you control', play: [{ mana: { per: 'tribe:Plant' } }] },
  { id: 'cra_canopycover', name: 'Canopy Cover', arch: 'farmer', set: 'Jungle', rarity: 'uncommon', cost: 1, type: 'spell', text: 'Add 3 mana', play: [{ mana: 3 }] },
  { id: 'cra_fertilesoil', name: 'Fertile Soil', arch: 'farmer', set: 'Jungle', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Add 6 mana', play: [{ mana: 6 }] },
  { id: 'cra_rapidgrowth', name: 'Rapid Growth', arch: 'farmer', set: 'Jungle', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Add 2 mana. Draw a card', play: [{ mana: 2 }, { draw: 1 }] },
  { id: 'cra_monsoon', name: 'Monsoon', arch: 'farmer', set: 'Jungle', rarity: 'uncommon', cost: 6, type: 'spell', text: 'Untap all your lands and mana-generating creatures', play: [{ untapAll: true }] },

  // ---- FARMER: Mountains (Uncommon) ----
  { id: 'cra_stonemoss', name: 'Stone Moss', arch: 'farmer', set: 'Mountains', rarity: 'uncommon', cost: 1, type: 'creature', atk: 0, hp: 3, tribe: 'Plant', text: 'When this takes damage, add 1 mana', damaged: [{ mana: 1 }] },
  { id: 'cra_ironroot', name: 'Iron Root', arch: 'farmer', set: 'Mountains', rarity: 'uncommon', cost: 2, type: 'creature', atk: 1, hp: 4, tribe: 'Plant', text: 'When this takes damage, add 1 mana', damaged: [{ mana: 1 }] },
  { id: 'cra_mountainthistle', name: 'Mountain Thistle', arch: 'farmer', set: 'Mountains', rarity: 'uncommon', cost: 2, type: 'creature', atk: 1, hp: 3, tribe: 'Plant', kw: ['taunt'], text: 'Taunt. When this takes damage, add 1 mana', damaged: [{ mana: 1 }] },
  { id: 'cra_granitelily', name: 'Granite Lily', arch: 'farmer', set: 'Mountains', rarity: 'uncommon', cost: 3, type: 'creature', atk: 0, hp: 5, tribe: 'Plant', text: 'When this takes damage, add 2 mana', damaged: [{ mana: 2 }] },
  { id: 'cra_ironbarkpine', name: 'Ironbark Pine', arch: 'farmer', set: 'Mountains', rarity: 'uncommon', cost: 4, type: 'creature', atk: 2, hp: 7, tribe: 'Plant', text: 'When this takes damage, add 1 mana. Other Mountain plants get +2 health', damaged: [{ mana: 1 }], aura: { h: 2, scope: 'tribe:Plant', other: true } },
  { id: 'cra_mineshaft', name: 'Mine Shaft', arch: 'farmer', set: 'Mountains', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Add 4 mana', play: [{ mana: 4 }] },
  { id: 'cra_excavate', name: 'Excavate', arch: 'farmer', set: 'Mountains', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Add 2 mana for each creature with Taunt you control', play: [{ mana: { n: 2, per: 'kw:taunt' } }] },
  { id: 'cra_gemstonevein', name: 'Gemstone Vein', arch: 'farmer', set: 'Mountains', rarity: 'uncommon', cost: 1, type: 'spell', text: 'Add 2 mana. Take 2 damage to player HP', play: [{ mana: 2 }, { loseHP: 2 }] },
  { id: 'cra_smelt', name: 'Smelt', arch: 'farmer', set: 'Mountains', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Sacrifice a creature. Add mana equal to its health', cost2: { sac: 1 }, play: [{ mana: { per: 'sacHealth' } }] },
  { id: 'cra_seismicsurge', name: 'Seismic Surge', arch: 'farmer', set: 'Mountains', rarity: 'uncommon', cost: 3, type: 'spell', text: "Add 5 mana. Your lands don't untap next turn", play: [{ mana: 5 }], manualNote: 'Lands do not untap next turn' },

  // ---- FARMER: Swamp (Rare) ----
  { id: 'cra_boglily', name: 'Bog Lily', arch: 'farmer', set: 'Swamp', rarity: 'rare', cost: 2, type: 'creature', atk: 0, hp: 3, tribe: 'Plant', text: 'Add 1 mana at start of your turn. When a creature dies anywhere, add 1 additional mana', startTurn: [{ mana: 1 }], anyDeath: [{ mana: 1 }] },
  { id: 'cra_mirecreeper', name: 'Mire Creeper', arch: 'farmer', set: 'Swamp', rarity: 'rare', cost: 2, type: 'creature', atk: 1, hp: 3, tribe: 'Plant', text: 'Add 1 mana at start of your turn. When this dies, all other Swamp plants add 1 additional mana next turn', startTurn: [{ mana: 1 }], manualNote: 'On death: other Swamp plants add +1 mana next turn' },
  { id: 'cra_corpseflower', name: 'Corpse Flower', arch: 'farmer', set: 'Swamp', rarity: 'rare', cost: 3, type: 'creature', atk: 1, hp: 4, tribe: 'Plant', text: 'Add 1 mana for each creature in the graveyard (max 5)', play: [{ mana: { per: 'graveCreatures', max: 5 } }] },
  { id: 'cra_blightedroot', name: 'Blighted Root', arch: 'farmer', set: 'Swamp', rarity: 'rare', cost: 1, type: 'creature', atk: 0, hp: 2, tribe: 'Plant', text: 'When this dies, add 3 mana', death: [{ mana: 3 }] },
  { id: 'cra_swampgas', name: 'Swamp Gas', arch: 'farmer', set: 'Swamp', rarity: 'rare', cost: 2, type: 'spell', text: 'Add 2 mana for each creature that died this turn', play: [{ mana: { n: 2, per: 'diedThisTurn' } }] },
  { id: 'cra_rotbloom', name: 'Rot Bloom', arch: 'farmer', set: 'Swamp', rarity: 'rare', cost: 3, type: 'spell', text: 'Sacrifice up to 3 plant creatures. Add 3 mana per plant sacrificed', cost2: { sacUpTo: 3, sacFilter: 'tribe:Plant' }, play: [{ mana: { n: 3, per: 'sacCount' } }] },
  { id: 'cra_fungalnetwork', name: 'Fungal Network', arch: 'farmer', set: 'Swamp', rarity: 'rare', cost: 4, type: 'tower', atk: 0, hp: 5, text: 'Tower. All your plant creatures gain "when this dies, add 2 mana"', manualNote: 'Plants grant 2 mana on death while this is up' },
  { id: 'cra_tarpit', name: 'Tar Pit', arch: 'farmer', set: 'Swamp', rarity: 'rare', cost: 3, type: 'spell', text: 'Destroy target enemy creature with 3 or less attack. Add mana equal to its cost', play: [{ t: 'enemy', filter: 'atkMax:3', destroyGainManaCost: true }] },
  { id: 'cra_miasma', name: 'Miasma', arch: 'farmer', set: 'Swamp', rarity: 'rare', cost: 3, type: 'spell', text: 'All enemy creatures get Poison 1. Add 1 mana for each creature poisoned', play: [{ t: 'allEnemy', poison: 1, manaPerTarget: 1 }] },
  { id: 'cra_witchsgarden', name: "Witch's Garden", arch: 'farmer', set: 'Swamp', rarity: 'rare', cost: 5, type: 'tower', atk: 0, hp: 6, text: 'Tower. At start of your turn, add mana equal to the number of creatures that died last round', startTurn: [{ mana: { per: 'diedLastRound' } }] },

  // ---- FARMER: Ambrosia (Legendary) ----
  { id: 'cra_ambrosiabloom', name: 'Ambrosia Bloom', arch: 'farmer', set: 'Ambrosia', rarity: 'legendary', cost: 7, type: 'tower', atk: 0, hp: 8, tribe: 'Plant', text: 'Tower. At start of your turn, add 5 mana and restore 5 player HP. All friendly plant creatures gain +1/+1 permanently each turn this is alive', startTurn: [{ mana: 5 }, { heal: 5 }, { t: 'allFriendly', filter: 'tribe:Plant', buffA: 1, buffH: 1, dur: 'perm' }] },
  { id: 'cra_nectarofthegods', name: 'Nectar of the Gods', arch: 'farmer', set: 'Ambrosia', rarity: 'legendary', cost: 6, type: 'spell', text: 'Restore all player HP to full. All friendly creatures gain +3/+3 permanently. Untap all lands and mana creatures', play: [{ healFull: true }, { t: 'allFriendly', buffA: 3, buffH: 3, dur: 'perm' }, { untapAll: true }] },

  // ---- ALCHEMIST: Apprentice (Starter) ----
  { id: 'cra_attackpotion', name: 'Attack Potion', arch: 'alchemist', set: 'Apprentice', rarity: 'starter', cost: 1, type: 'spell', text: 'Target creature gets +3 attack this turn', play: [{ t: 'creature', buffA: 3, dur: 'turn' }] },
  { id: 'cra_defenseelixir', name: 'Defense Elixir', arch: 'alchemist', set: 'Apprentice', rarity: 'starter', cost: 1, type: 'spell', text: 'Target creature gets +3 health this turn', play: [{ t: 'creature', buffH: 3, dur: 'turn' }] },
  { id: 'cra_healingpotion', name: 'Healing Potion', arch: 'alchemist', set: 'Apprentice', rarity: 'starter', cost: 1, type: 'spell', text: 'Restore 4 player HP', play: [{ heal: 4 }] },
  { id: 'cra_hastetonic', name: 'Haste Tonic', arch: 'alchemist', set: 'Apprentice', rarity: 'starter', cost: 1, type: 'spell', text: 'Target creature can attack immediately when played', play: [{ t: 'friendly', kw: ['haste'], dur: 'turn' }] },
  { id: 'cra_giantsdraught', name: "Giant's Draught", arch: 'alchemist', set: 'Apprentice', rarity: 'starter', cost: 2, type: 'spell', text: 'Target creature gets +5 attack this turn', play: [{ t: 'creature', buffA: 5, dur: 'turn' }] },
  { id: 'cra_stoneskinoil', name: 'Stoneskin Oil', arch: 'alchemist', set: 'Apprentice', rarity: 'starter', cost: 2, type: 'spell', text: 'Target creature takes no damage this turn', play: [{ t: 'creature', kw: ['immune'], dur: 'turn' }] },

  // ---- ALCHEMIST: Poisoner (Common) ----
  { id: 'cra_weakeningagent', name: 'Weakening Agent', arch: 'alchemist', set: 'Poisoner', rarity: 'common', cost: 1, type: 'spell', text: 'Target enemy creature gets -1 attack this turn', play: [{ t: 'enemy', buffA: -1, dur: 'turn' }] },
  { id: 'cra_cripplingtoxin', name: 'Crippling Toxin', arch: 'alchemist', set: 'Poisoner', rarity: 'common', cost: 1, type: 'spell', text: 'Target enemy creature gets -1 health', play: [{ t: 'enemy', buffH: -1, dur: 'perm' }] },
  { id: 'cra_blindingpowder', name: 'Blinding Powder', arch: 'alchemist', set: 'Poisoner', rarity: 'common', cost: 1, type: 'spell', text: 'Target enemy creature gets -1 attack for 2 turns', play: [{ t: 'enemy', buffA: -1, dur: 2 }] },
  { id: 'cra_numbingpoison', name: 'Numbing Poison', arch: 'alchemist', set: 'Poisoner', rarity: 'common', cost: 1, type: 'spell', text: 'Target enemy creature loses all abilities this turn', play: [{ t: 'enemy', suppress: true, dur: 'turn' }] },
  { id: 'cra_slowingsap', name: 'Slowing Sap', arch: 'alchemist', set: 'Poisoner', rarity: 'common', cost: 1, type: 'spell', text: 'Target enemy creature with Haste loses Haste this turn', play: [{ t: 'enemy', removeKw: ['haste'], dur: 'turn' }] },
  { id: 'cra_corrosivevial', name: 'Corrosive Vial', arch: 'alchemist', set: 'Poisoner', rarity: 'common', cost: 2, type: 'spell', text: 'Target enemy creature gets -1/-1', play: [{ t: 'enemy', buffA: -1, buffH: -1, dur: 'perm' }] },
  { id: 'cra_toxiccloud', name: 'Toxic Cloud', arch: 'alchemist', set: 'Poisoner', rarity: 'common', cost: 2, type: 'spell', text: 'All enemy creatures get -1 attack this turn', play: [{ t: 'allEnemy', buffA: -1, dur: 'turn' }] },
  { id: 'cra_nerveagent', name: 'Nerve Agent', arch: 'alchemist', set: 'Poisoner', rarity: 'common', cost: 1, type: 'spell', text: 'Target enemy creature gets Poison 1', play: [{ t: 'enemy', poison: 1 }] },
  { id: 'cra_sedative', name: 'Sedative', arch: 'alchemist', set: 'Poisoner', rarity: 'common', cost: 2, type: 'spell', text: 'Target enemy creature gets -2 attack this turn', play: [{ t: 'enemy', buffA: -2, dur: 'turn' }] },
  { id: 'cra_irritantsmoke', name: 'Irritant Smoke', arch: 'alchemist', set: 'Poisoner', rarity: 'common', cost: 2, type: 'spell', text: 'All enemy creatures get -1/-1 this turn', play: [{ t: 'allEnemy', buffA: -1, buffH: -1, dur: 'turn' }] },

  // ---- ALCHEMIST: Transmutation (Uncommon) ----
  { id: 'cra_leadentouch', name: 'Leaden Touch', arch: 'alchemist', set: 'Transmutation', rarity: 'uncommon', cost: 1, type: 'spell', text: 'Target enemy creature gets -2/-2. Add 1 mana', play: [{ t: 'enemy', buffA: -2, buffH: -2, dur: 'perm' }, { mana: 1 }] },
  { id: 'cra_gildedexchange', name: 'Gilded Exchange', arch: 'alchemist', set: 'Transmutation', rarity: 'uncommon', cost: 1, type: 'spell', text: 'Discard a card. Add 3 mana', cost2: { discard: 1 }, play: [{ mana: 3 }] },
  { id: 'cra_transmuteflesh', name: 'Transmute Flesh', arch: 'alchemist', set: 'Transmutation', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Sacrifice a creature. Add mana equal to its mana cost. Draw a card', cost2: { sac: 1 }, play: [{ mana: { per: 'sacCost' } }, { draw: 1 }] },
  { id: 'cra_refine', name: 'Refine', arch: 'alchemist', set: 'Transmutation', rarity: 'uncommon', cost: 1, type: 'spell', text: 'Discard 2 cards. Draw 2 cards. Add 1 mana', cost2: { discard: 2 }, play: [{ draw: 2 }, { mana: 1 }] },
  { id: 'cra_irontogold', name: 'Iron to Gold', arch: 'alchemist', set: 'Transmutation', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Destroy target equipment. Add 4 mana', play: [{ destroyT: { filter: 'equip', n: 1 } }, { mana: 4 }] },
  { id: 'cra_equivalentexchange', name: 'Equivalent Exchange', arch: 'alchemist', set: 'Transmutation', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Sacrifice a creature. Create a creature token with the same total stats but you choose the distribution', cost2: { sac: 1 }, manual: true },
  { id: 'cra_purify', name: 'Purify', arch: 'alchemist', set: 'Transmutation', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Remove all negative effects from target creature. Add 2 mana', play: [{ t: 'creature', cleanse: true }, { mana: 2 }] },
  { id: 'cra_recycle', name: 'Recycle', arch: 'alchemist', set: 'Transmutation', rarity: 'uncommon', cost: 1, type: 'spell', text: 'Destroy target friendly persistent or tower. Add mana equal to its cost plus 2', play: [{ destroyT: { filter: 'persistent,tower', side: 'friendly', n: 1 }, manaFromCostPlus: 2 }] },
  { id: 'cra_chrysopoeia', name: 'Chrysopoeia', arch: 'alchemist', set: 'Transmutation', rarity: 'uncommon', cost: 3, type: 'spell', text: "Target creature's mana cost becomes 0 for the purpose of resurrection and return-to-hand effects", manual: true },
  { id: 'cra_alchemicalconversion', name: 'Alchemical Conversion', arch: 'alchemist', set: 'Transmutation', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Convert up to 4 player HP into 4 mana', cost2: { loseHP: 4 }, play: [{ mana: 4 }] },

  // ---- ALCHEMIST: Unstable Concoctions (Uncommon) ----
  { id: 'cra_volatileflask', name: 'Volatile Flask', arch: 'alchemist', set: 'Unstable Concoctions', rarity: 'uncommon', cost: 1, type: 'spell', text: 'Flip: Deal 4 damage to target enemy creature OR deal 4 damage to a random friendly creature', play: [{ flip: { heads: [{ t: 'enemy', dmg: 4 }], tails: [{ t: 'randomFriendly', dmg: 4 }] } }] },
  { id: 'cra_bubblingbrew', name: 'Bubbling Brew', arch: 'alchemist', set: 'Unstable Concoctions', rarity: 'uncommon', cost: 1, type: 'spell', text: 'Flip: Target creature gets +4/+4 this turn OR target creature gets -4/-4', play: [{ flip: { heads: [{ t: 'creature', buffA: 4, buffH: 4, dur: 'turn' }], tails: [{ t: 'creature', buffA: -4, buffH: -4, dur: 'turn' }] } }] },
  { id: 'cra_unstableelixir', name: 'Unstable Elixir', arch: 'alchemist', set: 'Unstable Concoctions', rarity: 'uncommon', cost: 1, type: 'spell', text: 'Flip: Add 5 mana OR lose 5 mana', play: [{ flip: { heads: [{ mana: 5 }], tails: [{ loseMana: 5 }] } }] },
  { id: 'cra_fizzingvial', name: 'Fizzing Vial', arch: 'alchemist', set: 'Unstable Concoctions', rarity: 'uncommon', cost: 1, type: 'spell', text: 'Flip: Restore 6 player HP OR lose 3 player HP', play: [{ flip: { heads: [{ heal: 6 }], tails: [{ loseHP: 3 }] } }] },
  { id: 'cra_wildtonic', name: 'Wild Tonic', arch: 'alchemist', set: 'Unstable Concoctions', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Flip: Draw 3 cards OR discard 2 cards', play: [{ flip: { heads: [{ draw: 3 }], tails: [{ discardRandom: 2 }] } }] },
  { id: 'cra_chaoticmixture', name: 'Chaotic Mixture', arch: 'alchemist', set: 'Unstable Concoctions', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Flip: Target enemy creature gets -3/-3 OR target friendly creature gets -3/-3', play: [{ flip: { heads: [{ t: 'enemy', buffA: -3, buffH: -3, dur: 'perm' }], tails: [{ t: 'randomFriendly', buffA: -3, buffH: -3, dur: 'perm' }] } }] },
  { id: 'cra_explosivecompound', name: 'Explosive Compound', arch: 'alchemist', set: 'Unstable Concoctions', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Flip: Deal 5 damage to target enemy creature OR deal 3 damage to all friendly creatures', play: [{ flip: { heads: [{ t: 'enemy', dmg: 5 }], tails: [{ t: 'allFriendly', dmg: 3 }] } }] },
  { id: 'cra_mysterydraught', name: 'Mystery Draught', arch: 'alchemist', set: 'Unstable Concoctions', rarity: 'uncommon', cost: 2, type: 'spell', text: "Flip: Target creature gains Haste and +3 attack this turn OR target creature can't attack this turn", play: [{ flip: { heads: [{ t: 'creature', kw: ['haste'], buffA: 3, dur: 'turn' }], tails: [{ t: 'creature', cantAttack: 1 }] } }] },
  { id: 'cra_alchemistsgambit', name: "Alchemist's Gambit", arch: 'alchemist', set: 'Unstable Concoctions', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Flip: Target creature gets +3/+3 permanently OR target creature dies', play: [{ flip: { heads: [{ t: 'creature', buffA: 3, buffH: 3, dur: 'perm' }], tails: [{ t: 'creature', destroy: true }] } }] },
  { id: 'cra_bottledchaos', name: 'Bottled Chaos', arch: 'alchemist', set: 'Unstable Concoctions', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Flip: Deal 8 damage to target OR deal 8 damage to player HP', play: [{ flip: { heads: [{ t: 'any', dmg: 8 }], tails: [{ loseHP: 8 }] } }] },

  // ---- ALCHEMIST: Philosopher's Stone (Rare) ----
  { id: 'cra_mercuryflask', name: 'Mercury Flask', arch: 'alchemist', set: "Philosopher's Stone", rarity: 'rare', cost: 2, type: 'persistent', atk: 0, hp: 2, component: true, text: 'Persistent. Add 1 mana at start of your turn', startTurn: [{ mana: 1 }] },
  { id: 'cra_sulfurcrucible', name: 'Sulfur Crucible', arch: 'alchemist', set: "Philosopher's Stone", rarity: 'rare', cost: 2, type: 'persistent', atk: 0, hp: 2, component: true, text: 'Persistent. Your spells deal 1 additional damage', manualNote: 'Spells deal +1 damage while on board' },
  { id: 'cra_saltcrystal', name: 'Salt Crystal', arch: 'alchemist', set: "Philosopher's Stone", rarity: 'rare', cost: 2, type: 'persistent', atk: 0, hp: 2, component: true, text: 'Persistent. All your consumable spells cost 1 less', costMod: { type: 'spell', delta: -1 } },
  { id: 'cra_azothflame', name: 'Azoth Flame', arch: 'alchemist', set: "Philosopher's Stone", rarity: 'rare', cost: 2, type: 'persistent', atk: 0, hp: 2, component: true, text: 'Persistent. When you play a spell, draw a card', ownerSpell: [{ draw: 1 }] },
  { id: 'cra_calcination', name: 'Calcination', arch: 'alchemist', set: "Philosopher's Stone", rarity: 'rare', cost: 1, type: 'spell', text: 'Deal 2 damage to target creature. If you control 2+ components, deal 4 instead', play: [{ t: 'creature', cond: { components: 2 }, dmg: 4, elseDmg: 2 }] },
  { id: 'cra_dissolution', name: 'Dissolution', arch: 'alchemist', set: "Philosopher's Stone", rarity: 'rare', cost: 1, type: 'spell', text: 'Restore 3 player HP. If you control 2+ components, restore 6 instead', play: [{ cond: { components: 2 }, heal: 6, elseHeal: 3 }] },
  { id: 'cra_coagulation', name: 'Coagulation', arch: 'alchemist', set: "Philosopher's Stone", rarity: 'rare', cost: 2, type: 'spell', text: "Target creature gets +2/+2 this turn. If you control 3+ components, it's permanent", play: [{ t: 'creature', cond: { components: 3 }, buffA: 2, buffH: 2, dur: 'perm', elseDur: 'turn' }] },
  { id: 'cra_sublimation', name: 'Sublimation', arch: 'alchemist', set: "Philosopher's Stone", rarity: 'rare', cost: 2, type: 'spell', text: 'Add 3 mana. If you control 3+ components, add 6 instead', play: [{ cond: { components: 3 }, mana: 6, elseMana: 3 }] },
  { id: 'cra_magnumopus', name: 'Magnum Opus', arch: 'alchemist', set: "Philosopher's Stone", rarity: 'rare', cost: 4, type: 'spell', text: 'If you control all 4 components, transform them into the Philosopher\'s Stone', play: [{ magnumOpus: true }] },
  { id: 'cra_philosophersstone', name: "Philosopher's Stone", arch: 'alchemist', set: "Philosopher's Stone", rarity: 'rare', cost: 0, type: 'persistent', atk: 0, hp: 8, uncollectible: true, text: 'Persistent. All friendly creatures get +2/+2. All spells cost 2 less. Restore 3 player HP at start of each turn. Add 3 mana at start of each turn', aura: { a: 2, h: 2, scope: 'friendly' }, costMod: { type: 'spell', delta: -2 }, startTurn: [{ heal: 3 }, { mana: 3 }] },

  // ---- ALCHEMIST: Truth (Legendary) ----
  { id: 'cra_truth', name: 'Truth', arch: 'alchemist', set: 'Truth', rarity: 'legendary', cost: 8, type: 'creature', atk: 3, hp: 6, text: 'While Truth is on the board, all friendly spells cost 1. All friendly creatures cost half their mana cost (rounded up)', truthAura: true },
  { id: 'cra_lawofexchange', name: 'Law of Exchange', arch: 'alchemist', set: 'Truth', rarity: 'legendary', cost: 5, type: 'spell', text: 'This turn, every card any player plays costs 0. At end of turn, lose player HP equal to the total mana cost of all cards played this way', manual: true },
];
