// SORCERER — Black. Graveyard interaction, resource manipulation.
module.exports = [
  // ---- Class Staples ----
  { id: 'sor_gravepeek', name: 'Grave Peek', arch: null, set: 'Staples', rarity: 'starter', cost: 1, type: 'spell', text: 'Look at the top 5 cards of graveyard. Put one in your hand', play: [{ peek: { deck: 'grave', n: 5, takeToHand: 1 } }] },
  { id: 'sor_soultap', name: 'Soul Tap', arch: null, set: 'Staples', rarity: 'starter', cost: 1, type: 'spell', text: 'Sacrifice a creature. Add 2 mana', cost2: { sac: 1 }, play: [{ mana: 2 }] },
  { id: 'sor_darkbargain', name: 'Dark Bargain', arch: null, set: 'Staples', rarity: 'starter', cost: 2, type: 'spell', text: 'Discard a card. Draw 2 cards', cost2: { discard: 1 }, play: [{ draw: 2 }] },
  { id: 'sor_reclaim', name: 'Reclaim', arch: null, set: 'Staples', rarity: 'starter', cost: 2, type: 'spell', text: "Return target card from graveyard to owner's hand", play: [{ reclaim: { n: 1 } }] },

  // ---- NECROMANCER: Grave (Starter) ----
  { id: 'sor_raisedead', name: 'Raise Dead', arch: 'necromancer', set: 'Grave', rarity: 'starter', cost: 1, type: 'spell', text: 'Return creature cost 2 or less from graveyard to board', play: [{ rez: { max: 2, n: 1 } }] },
  { id: 'sor_shallowgrave', name: 'Shallow Grave', arch: 'necromancer', set: 'Grave', rarity: 'starter', cost: 2, type: 'spell', text: 'Return creature from graveyard to board. Destroy at end of turn', play: [{ rez: { n: 1, temp: true } }] },
  { id: 'sor_boneservant', name: 'Bone Servant', arch: 'necromancer', set: 'Grave', rarity: 'starter', cost: 2, type: 'creature', atk: 2, hp: 2, text: 'On death, return cost 1 or less creature to board', death: [{ rez: { max: 1, n: 1 } }] },
  { id: 'sor_revive', name: 'Revive', arch: 'necromancer', set: 'Grave', rarity: 'starter', cost: 3, type: 'spell', text: 'Return creature cost 3 or less from graveyard to board', play: [{ rez: { max: 3, n: 1 } }] },
  { id: 'sor_gravekeeper', name: 'Gravekeeper', arch: 'necromancer', set: 'Grave', rarity: 'starter', cost: 3, type: 'creature', atk: 2, hp: 3, text: 'Once per turn, return cost 1 or less to hand', activated: { name: 'Reclaim (cost 1 or less)', oncePerTurn: true, actions: [{ reclaim: { max: 1, n: 1 } }] } },
  { id: 'sor_massrevival', name: 'Mass Revival', arch: 'necromancer', set: 'Grave', rarity: 'starter', cost: 5, type: 'spell', text: 'Return up to 3 creatures cost 2 or less to board', play: [{ rez: { max: 2, n: 3, upTo: true } }] },

  // ---- NECROMANCER: Bone (Common) ----
  { id: 'sor_bonescatter', name: 'Bone Scatter', arch: 'necromancer', set: 'Bone', rarity: 'common', cost: 1, type: 'spell', text: 'Return a creature with cost 1 or less from graveyard to board', play: [{ rez: { max: 1, n: 1 } }] },
  { id: 'sor_boneyardharvest', name: 'Boneyard Harvest', arch: 'necromancer', set: 'Bone', rarity: 'common', cost: 2, type: 'spell', text: 'Return up to 2 creatures with cost 1 or less from graveyard to board', play: [{ rez: { max: 1, n: 2, upTo: true } }] },
  { id: 'sor_bonewall', name: 'Bone Wall', arch: 'necromancer', set: 'Bone', rarity: 'common', cost: 2, type: 'spell', text: 'Return a creature with cost 1 or less from graveyard to board with Taunt and +2 health', play: [{ rez: { max: 1, n: 1, h: 2, kw: ['taunt'] } }] },
  { id: 'sor_skeletalswarm', name: 'Skeletal Swarm', arch: 'necromancer', set: 'Bone', rarity: 'common', cost: 3, type: 'spell', text: 'Return up to 3 creatures with cost 1 or less from graveyard to board', play: [{ rez: { max: 1, n: 3, upTo: true } }] },
  { id: 'sor_bonecollector', name: 'Bone Collector', arch: 'necromancer', set: 'Bone', rarity: 'common', cost: 2, type: 'creature', atk: 1, hp: 3, text: 'When another creature with cost 1 dies, return it to board at end of turn', manual: true },
  { id: 'sor_bonepile', name: 'Bone Pile', arch: 'necromancer', set: 'Bone', rarity: 'common', cost: 1, type: 'persistent', atk: 0, hp: 2, text: 'At start of your turn, if 5+ creatures in graveyard, return a cost 1 or less creature to board', startTurn: [{ cond: { graveCreatures: 5 }, rez: { max: 1, n: 1 } }] },
  { id: 'sor_reassemble', name: 'Reassemble', arch: 'necromancer', set: 'Bone', rarity: 'common', cost: 1, type: 'spell', text: 'Return a creature with cost 2 or less from graveyard to your hand', play: [{ reclaim: { max: 2, n: 1, typeFilter: 'creature' } }] },
  { id: 'sor_bonepuppeteer', name: 'Bone Puppeteer', arch: 'necromancer', set: 'Bone', rarity: 'common', cost: 3, type: 'creature', atk: 2, hp: 2, text: 'Once per turn, return a creature with cost 1 or less from graveyard to board', activated: { name: 'Raise (cost 1 or less)', oncePerTurn: true, actions: [{ rez: { max: 1, n: 1 } }] } },
  { id: 'sor_massexhume', name: 'Mass Exhume', arch: 'necromancer', set: 'Bone', rarity: 'common', cost: 4, type: 'spell', text: 'Return up to 4 creatures with cost 1 or less from graveyard to board', play: [{ rez: { max: 1, n: 4, upTo: true } }] },
  { id: 'sor_rattlingmarch', name: 'Rattling March', arch: 'necromancer', set: 'Bone', rarity: 'common', cost: 3, type: 'spell', text: 'Return up to 2 creatures with cost 1 or less from graveyard to board. They get +1/+1', play: [{ rez: { max: 1, n: 2, upTo: true, a: 1, h: 1 } }] },

  // ---- NECROMANCER: Spirit (Common) ----
  { id: 'sor_spiritcall', name: 'Spirit Call', arch: 'necromancer', set: 'Spirit', rarity: 'common', cost: 1, type: 'spell', text: 'Return a creature with cost 3 or less from graveyard to board. Destroy it at end of turn', play: [{ rez: { max: 3, n: 1, temp: true } }] },
  { id: 'sor_lingeringghost', name: 'Lingering Ghost', arch: 'necromancer', set: 'Spirit', rarity: 'common', cost: 1, type: 'spell', text: 'Return a creature with cost 2 or less from graveyard to board. Destroy it at end of turn', play: [{ rez: { max: 2, n: 1, temp: true } }] },
  { id: 'sor_spectralsummon', name: 'Spectral Summon', arch: 'necromancer', set: 'Spirit', rarity: 'common', cost: 2, type: 'spell', text: 'Return a creature with cost 4 or less from graveyard to board. Destroy it at end of turn', play: [{ rez: { max: 4, n: 1, temp: true } }] },
  { id: 'sor_ghostlyvengeance', name: 'Ghostly Vengeance', arch: 'necromancer', set: 'Spirit', rarity: 'common', cost: 2, type: 'spell', text: 'Return a creature from graveyard to board. It gains Haste. Destroy it at end of turn', play: [{ rez: { n: 1, temp: true, kw: ['haste'] } }] },
  { id: 'sor_fleetingreturn', name: 'Fleeting Return', arch: 'necromancer', set: 'Spirit', rarity: 'common', cost: 1, type: 'spell', text: 'Return a creature with cost 2 or less from graveyard to board. It may attack immediately. Destroy it at end of turn', play: [{ rez: { max: 2, n: 1, temp: true, kw: ['haste'] } }] },
  { id: 'sor_spiritprocession', name: 'Spirit Procession', arch: 'necromancer', set: 'Spirit', rarity: 'common', cost: 3, type: 'spell', text: 'Return up to 2 creatures with cost 3 or less from graveyard to board. Destroy them at end of turn', play: [{ rez: { max: 3, n: 2, upTo: true, temp: true } }] },
  { id: 'sor_hauntedecho', name: 'Haunted Echo', arch: 'necromancer', set: 'Spirit', rarity: 'common', cost: 2, type: 'spell', text: 'Return a creature from graveyard to board with half stats. Destroy it at end of turn', play: [{ rez: { n: 1, temp: true, half: true } }] },
  { id: 'sor_finalfarewell', name: 'Final Farewell', arch: 'necromancer', set: 'Spirit', rarity: 'common', cost: 2, type: 'spell', text: 'Return a creature with cost 3 or less from graveyard to board. It gets +2 attack. Destroy it at end of turn. Exile it', play: [{ rez: { max: 3, n: 1, temp: true, a: 2, exileAfter: true } }] },
  { id: 'sor_spiritmedium', name: 'Spirit Medium', arch: 'necromancer', set: 'Spirit', rarity: 'common', cost: 2, type: 'creature', atk: 1, hp: 2, text: 'Once per turn, return a creature with cost 2 or less from graveyard to board. Destroy it at end of turn', activated: { name: 'Summon spirit (cost 2 or less)', oncePerTurn: true, actions: [{ rez: { max: 2, n: 1, temp: true } }] } },
  { id: 'sor_afterimage', name: 'Afterimage', arch: 'necromancer', set: 'Spirit', rarity: 'common', cost: 1, type: 'reaction', text: 'Reaction: When a friendly creature dies, return it to board with 1 health. Destroy it at end of turn', reaction: { on: 'allyDeath' }, play: [{ rezSubject: { hp1: true, temp: true } }] },

  // ---- NECROMANCER: Crypt (Uncommon) ----
  { id: 'sor_cryptawakening', name: 'Crypt Awakening', arch: 'necromancer', set: 'Crypt', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Return a creature with cost 3 or less from graveyard to board. It gets +1/+1 permanently', play: [{ rez: { max: 3, n: 1, a: 1, h: 1 } }] },
  { id: 'sor_empoweredreturn', name: 'Empowered Return', arch: 'necromancer', set: 'Crypt', rarity: 'uncommon', cost: 4, type: 'spell', text: 'Return a creature with cost 4 or less from graveyard to board. It gets +2/+2 permanently', play: [{ rez: { max: 4, n: 1, a: 2, h: 2 } }] },
  { id: 'sor_vengefuldead', name: 'Vengeful Dead', arch: 'necromancer', set: 'Crypt', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Return a creature from graveyard to board. It gains +2 attack permanently. It must attack each turn if able', play: [{ rez: { n: 1, a: 2 } }], manualNote: 'Must attack each turn if able' },
  { id: 'sor_undyingchampion', name: 'Undying Champion', arch: 'necromancer', set: 'Crypt', rarity: 'uncommon', cost: 3, type: 'creature', atk: 2, hp: 3, text: 'When this dies, return it to board with +1/+1 permanently. Can only trigger twice', manual: true },
  { id: 'sor_bolsteredrevival', name: 'Bolstered Revival', arch: 'necromancer', set: 'Crypt', rarity: 'uncommon', cost: 4, type: 'spell', text: 'Return a creature with cost 4 or less from graveyard to board. It gains a keyword of your choice from: Taunt, Trample, First Strike, Lifelink', play: [{ rez: { max: 4, n: 1, kwPick: ['taunt', 'trample', 'firststrike', 'lifelink'] } }] },
  { id: 'sor_darkrebirth', name: 'Dark Rebirth', arch: 'necromancer', set: 'Crypt', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Return a creature with cost 3 or less from graveyard to board. It gains "when this dies, return it to your hand"', play: [{ rez: { max: 3, n: 1, returnHandOnDeath: true } }] },
  { id: 'sor_cryptguardian', name: 'Crypt Guardian', arch: 'necromancer', set: 'Crypt', rarity: 'uncommon', cost: 4, type: 'creature', atk: 3, hp: 3, text: 'When a friendly creature is returned from the graveyard, it gets +1/+1 permanently', rezTrigger: [{ t: 'rezSubject', buffA: 1, buffH: 1, dur: 'perm' }] },
  { id: 'sor_improvedresurrection', name: 'Improved Resurrection', arch: 'necromancer', set: 'Crypt', rarity: 'uncommon', cost: 5, type: 'spell', text: 'Return a creature with cost 5 or less from graveyard to board. It gets +2/+2 permanently and gains Shield 2', play: [{ rez: { max: 5, n: 1, a: 2, h: 2, shield: 2 } }] },
  { id: 'sor_fortifiedrevival', name: 'Fortified Revival', arch: 'necromancer', set: 'Crypt', rarity: 'uncommon', cost: 4, type: 'spell', text: 'Return a creature from graveyard to board with double its original health', play: [{ rez: { n: 1, dblHp: true } }] },
  { id: 'sor_graveempowerment', name: 'Grave Empowerment', arch: 'necromancer', set: 'Crypt', rarity: 'uncommon', cost: 3, type: 'persistent', atk: 0, hp: 3, text: 'All creatures you return from the graveyard get +1 attack permanently', rezTrigger: [{ t: 'rezSubject', buffA: 1, dur: 'perm' }] },

  // ---- NECROMANCER: Plague (Uncommon) ----
  { id: 'sor_plaguebearer2', name: 'Plague Bearer', arch: 'necromancer', set: 'Plague', rarity: 'uncommon', cost: 2, type: 'creature', atk: 2, hp: 1, text: 'When this dies, return a creature with cost 1 or less from graveyard to board', death: [{ rez: { max: 1, n: 1 } }] },
  { id: 'sor_infectiousreturn', name: 'Infectious Return', arch: 'necromancer', set: 'Plague', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Return a creature with cost 3 or less from graveyard to board. When it dies, return another creature with cost 2 or less from graveyard to board', play: [{ rez: { max: 3, n: 1, chainOnDeath: 2 } }] },
  { id: 'sor_plaguerat', name: 'Plague Rat', arch: 'necromancer', set: 'Plague', rarity: 'uncommon', cost: 1, type: 'creature', atk: 1, hp: 1, tribe: 'Rat', text: 'When this dies, return another Plague Rat from graveyard to board if one exists', death: [{ rez: { n: 1, nameFilter: 'Plague Rat' } }] },
  { id: 'sor_deathchain', name: 'Death Chain', arch: 'necromancer', set: 'Plague', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Return a creature with cost 2 or less from graveyard to board. When it dies this turn, repeat this effect once', play: [{ rez: { max: 2, n: 1, chainOnDeath: 2, chainOnce: true } }] },
  { id: 'sor_spreadingdeath', name: 'Spreading Death', arch: 'necromancer', set: 'Plague', rarity: 'uncommon', cost: 4, type: 'spell', text: 'Return a creature from graveyard to board. When it dies, return up to 2 creatures with cost 2 or less from graveyard to board', manual: true },
  { id: 'sor_festeringcorpse', name: 'Festering Corpse', arch: 'necromancer', set: 'Plague', rarity: 'uncommon', cost: 2, type: 'creature', atk: 1, hp: 2, text: 'When this dies, return a creature with cost 1 or less from graveyard to board and deal 1 damage to all enemy creatures', death: [{ rez: { max: 1, n: 1 } }, { t: 'allEnemy', dmg: 1 }] },
  { id: 'sor_plaguedoctor', name: 'Plague Doctor', arch: 'necromancer', set: 'Plague', rarity: 'uncommon', cost: 3, type: 'creature', atk: 2, hp: 3, text: 'When any friendly creature dies, you may return a creature with cost 1 or less from graveyard to your hand', allyDeath: [{ reclaim: { max: 1, n: 1, optional: true } }] },
  { id: 'sor_outbreak', name: 'Outbreak', arch: 'necromancer', set: 'Plague', rarity: 'uncommon', cost: 4, type: 'spell', text: 'Return up to 3 creatures with cost 2 or less from graveyard to board. Each gains "when this dies, deal 1 damage to a random enemy creature"', play: [{ rez: { max: 2, n: 3, upTo: true, deathDmg: 1 } }] },
  { id: 'sor_patientzero', name: 'Patient Zero', arch: 'necromancer', set: 'Plague', rarity: 'uncommon', cost: 3, type: 'creature', atk: 1, hp: 1, text: 'When this dies, return 2 creatures with cost 2 or less from graveyard to board', death: [{ rez: { max: 2, n: 2, upTo: true } }] },
  { id: 'sor_pandemic', name: 'Pandemic', arch: 'necromancer', set: 'Plague', rarity: 'uncommon', cost: 5, type: 'persistent', atk: 0, hp: 3, text: 'When a friendly creature dies, return a creature with lower cost from graveyard to board', allyDeath: [{ rez: { n: 1, lowerCostThanSubject: true } }] },

  // ---- NECROMANCER: Revenant (Rare) ----
  { id: 'sor_revenantcall', name: 'Revenant Call', arch: 'necromancer', set: 'Revenant', rarity: 'rare', cost: 5, type: 'spell', text: 'Return any creature from graveyard to board', play: [{ rez: { n: 1 } }] },
  { id: 'sor_greaterrevival', name: 'Greater Revival', arch: 'necromancer', set: 'Revenant', rarity: 'rare', cost: 6, type: 'spell', text: 'Return any creature from graveyard to board. It gets +2/+2 permanently', play: [{ rez: { n: 1, a: 2, h: 2 } }] },
  { id: 'sor_undeatheternal', name: 'Undeath Eternal', arch: 'necromancer', set: 'Revenant', rarity: 'rare', cost: 5, type: 'spell', text: 'Return any creature from graveyard to board. It gains "when this dies, return it to your hand"', play: [{ rez: { n: 1, returnHandOnDeath: true } }] },
  { id: 'sor_soulanchor', name: 'Soul Anchor', arch: 'necromancer', set: 'Revenant', rarity: 'rare', cost: 5, type: 'persistent', atk: 0, hp: 3, text: 'When a friendly creature with cost 4+ dies, return it to board with 1 health at start of your next turn', manual: true },
  { id: 'sor_revenantknight', name: 'Revenant Knight', arch: 'necromancer', set: 'Revenant', rarity: 'rare', cost: 6, type: 'creature', atk: 4, hp: 4, text: 'When this dies, return the highest cost creature from graveyard to board', death: [{ rez: { n: 1, highestCost: true } }] },
  { id: 'sor_trueresurrection', name: 'True Resurrection', arch: 'necromancer', set: 'Revenant', rarity: 'rare', cost: 7, type: 'spell', text: 'Return any creature from graveyard to board with full stats, all equipment it had when it died, and +3/+3 permanently', play: [{ rez: { n: 1, a: 3, h: 3 } }], manualNote: 'Re-attach its equipment manually' },
  { id: 'sor_massrevenant', name: 'Mass Revenant', arch: 'necromancer', set: 'Revenant', rarity: 'rare', cost: 7, type: 'spell', text: 'Return up to 2 creatures of any cost from graveyard to board', play: [{ rez: { n: 2, upTo: true } }] },
  { id: 'sor_defydeath', name: 'Defy Death', arch: 'necromancer', set: 'Revenant', rarity: 'rare', cost: 5, type: 'reaction', text: 'Reaction: When a friendly creature would die, return it to board with 1 health instead. Exile a card from graveyard', reaction: { on: 'wouldDie' }, cost2: { exile: 1 }, play: [{ survive: 1 }] },
  { id: 'sor_revenantlord', name: 'Revenant Lord', arch: 'necromancer', set: 'Revenant', rarity: 'rare', cost: 6, type: 'creature', atk: 3, hp: 4, text: 'At start of your turn, return a creature with cost 3 or less from graveyard to board', startTurn: [{ rez: { max: 3, n: 1 } }] },
  { id: 'sor_immortalbinding', name: 'Immortal Binding', arch: 'necromancer', set: 'Revenant', rarity: 'rare', cost: 7, type: 'persistent', atk: 0, hp: 4, text: 'All friendly creatures gain "when this dies, return it to graveyard instead of exile." Once per round, return a creature of any cost from graveyard to board', activated: { name: 'Raise any creature', oncePerTurn: true, actions: [{ rez: { n: 1 } }] } },

  // ---- NECROMANCER: Eternal (Legendary) ----
  { id: 'sor_eternalsovereign', name: 'Eternal Sovereign', arch: 'necromancer', set: 'Eternal', rarity: 'legendary', cost: 9, type: 'creature', atk: 5, hp: 5, text: 'At start of your turn, return any creature from graveyard to board with +2/+2 permanently. When this dies, exile 10 creatures from graveyard to return it to board with 1 health', startTurn: [{ rez: { n: 1, a: 2, h: 2 } }], manualNote: 'Death-defiance (exile 10 creatures) is resolved manually' },
  { id: 'sor_undyingarmy', name: 'Undying Army', arch: 'necromancer', set: 'Eternal', rarity: 'legendary', cost: 8, type: 'spell', text: 'For the rest of this encounter, whenever a friendly creature dies, return it to board at start of your next turn with 1 health. Each creature can only be returned this way once', manual: true },

  // ---- DARK RITUALIST: Dark Ritual (Starter) ----
  { id: 'sor_bloodoffering', name: 'Blood Offering', arch: 'ritualist', set: 'Dark Ritual', rarity: 'starter', cost: 1, type: 'spell', text: 'Sacrifice a creature. Draw 2 cards', cost2: { sac: 1 }, play: [{ draw: 2 }] },
  { id: 'sor_ritualcandle', name: 'Ritual Candle', arch: 'ritualist', set: 'Dark Ritual', rarity: 'starter', cost: 1, type: 'persistent', atk: 0, hp: 1, text: 'Persistent. Sacrifice this: Add 3 mana', activated: { name: 'Sacrifice: add 3 mana', sacSelf: true, actions: [{ mana: 3 }] } },
  { id: 'sor_gatheringpower', name: 'Gathering Power', arch: 'ritualist', set: 'Dark Ritual', rarity: 'starter', cost: 2, type: 'spell', text: 'Deal damage equal to spells in graveyard (max 5)', play: [{ t: 'any', dmg: { per: 'graveSpells', max: 5 } }] },
  { id: 'sor_soulharvest', name: 'Soul Harvest', arch: 'ritualist', set: 'Dark Ritual', rarity: 'starter', cost: 2, type: 'spell', text: 'Add 1 mana per creature in graveyard (max 5)', play: [{ mana: { per: 'graveCreatures', max: 5 } }] },
  { id: 'sor_darkpact', name: 'Dark Pact', arch: 'ritualist', set: 'Dark Ritual', rarity: 'starter', cost: 3, type: 'spell', text: 'Sacrifice 2 creatures. Draw 4 cards', cost2: { sac: 2 }, play: [{ draw: 4 }] },
  { id: 'sor_ritualcircle', name: 'Ritual Circle', arch: 'ritualist', set: 'Dark Ritual', rarity: 'starter', cost: 4, type: 'persistent', atk: 0, hp: 2, text: 'Persistent. If 10+ cards in graveyard, add 3 mana at turn start', startTurn: [{ cond: { grave: 10 }, mana: 3 }] },

  // ---- DARK RITUALIST: Blood (Common) ----
  { id: 'sor_blooddraw', name: 'Blood Draw', arch: 'ritualist', set: 'Blood', rarity: 'common', cost: 1, type: 'spell', text: 'Sacrifice a creature. Draw 2 cards', cost2: { sac: 1 }, play: [{ draw: 2 }] },
  { id: 'sor_bloodburst', name: 'Blood Burst', arch: 'ritualist', set: 'Blood', rarity: 'common', cost: 1, type: 'spell', text: 'Sacrifice a creature. Add 3 mana', cost2: { sac: 1 }, play: [{ mana: 3 }] },
  { id: 'sor_bloodstrike', name: 'Blood Strike', arch: 'ritualist', set: 'Blood', rarity: 'common', cost: 1, type: 'spell', text: 'Sacrifice a creature. Deal 3 damage to target', cost2: { sac: 1 }, play: [{ t: 'any', dmg: 3 }] },
  { id: 'sor_bloodshield', name: 'Blood Shield', arch: 'ritualist', set: 'Blood', rarity: 'common', cost: 1, type: 'spell', text: "Sacrifice a creature. Gain player shield equal to the sacrificed creature's health", cost2: { sac: 1 }, play: [{ shield: { per: 'sacHealth' } }] },
  { id: 'sor_bloodfuel', name: 'Blood Fuel', arch: 'ritualist', set: 'Blood', rarity: 'common', cost: 1, type: 'spell', text: 'Sacrifice a creature. Add mana equal to its mana cost', cost2: { sac: 1 }, play: [{ mana: { per: 'sacCost' } }] },
  { id: 'sor_bloodpact2', name: 'Blood Pact', arch: 'ritualist', set: 'Blood', rarity: 'common', cost: 2, type: 'spell', text: 'Sacrifice a creature. Target creature gets +2/+2 this turn', cost2: { sac: 1 }, play: [{ t: 'creature', buffA: 2, buffH: 2, dur: 'turn' }] },
  { id: 'sor_bloodprice', name: 'Blood Price', arch: 'ritualist', set: 'Blood', rarity: 'common', cost: 2, type: 'spell', text: 'Sacrifice a creature. Draw cards equal to its mana cost (max 3)', cost2: { sac: 1 }, play: [{ draw: { per: 'sacCost', max: 3 } }] },
  { id: 'sor_bloodchanneler', name: 'Blood Channeler', arch: 'ritualist', set: 'Blood', rarity: 'common', cost: 2, type: 'creature', atk: 1, hp: 2, text: 'Once per turn, sacrifice another creature to add 2 mana', activated: { name: 'Sacrifice a creature: add 2 mana', oncePerTurn: true, cost: { sac: 1 }, actions: [{ mana: 2 }] } },
  { id: 'sor_bloodrush', name: 'Blood Rush', arch: 'ritualist', set: 'Blood', rarity: 'common', cost: 2, type: 'spell', text: 'Sacrifice a creature. Target creature gains Haste and +1 attack this turn', cost2: { sac: 1 }, play: [{ t: 'creature', kw: ['haste'], buffA: 1, dur: 'turn' }] },
  { id: 'sor_crimsonharvest', name: 'Crimson Harvest', arch: 'ritualist', set: 'Blood', rarity: 'common', cost: 3, type: 'spell', text: 'Sacrifice up to 2 creatures. For each, draw a card and add 2 mana', cost2: { sacUpTo: 2 }, play: [{ draw: { per: 'sacCount' }, mana: { n: 2, per: 'sacCount' } }] },

  // ---- DARK RITUALIST: Cult (Uncommon) ----
  { id: 'sor_cultgathering', name: 'Cult Gathering', arch: 'ritualist', set: 'Cult', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Sacrifice 2 creatures. Draw 4 cards', cost2: { sac: 2 }, play: [{ draw: 4 }] },
  { id: 'sor_massoffering', name: 'Mass Offering', arch: 'ritualist', set: 'Cult', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Sacrifice up to 3 creatures. Add 3 mana per creature sacrificed', cost2: { sacUpTo: 3 }, play: [{ mana: { n: 3, per: 'sacCount' } }] },
  { id: 'sor_ritualsacrifice', name: 'Ritual Sacrifice', arch: 'ritualist', set: 'Cult', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Sacrifice 2 creatures. Deal damage equal to their combined attack to target', cost2: { sac: 2 }, play: [{ t: 'any', dmg: { per: 'sacAttack' } }] },
  { id: 'sor_cultfanatic', name: 'Cult Fanatic', arch: 'ritualist', set: 'Cult', rarity: 'uncommon', cost: 2, type: 'creature', atk: 1, hp: 1, text: 'When another creature is sacrificed, this gets +1/+1 permanently', sacTrigger: [{ t: 'self', buffA: 1, buffH: 1, dur: 'perm' }] },
  { id: 'sor_darkcongregation', name: 'Dark Congregation', arch: 'ritualist', set: 'Cult', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Sacrifice 3 creatures. Target creature gets +3/+3 permanently', cost2: { sac: 3 }, play: [{ t: 'creature', buffA: 3, buffH: 3, dur: 'perm' }] },
  { id: 'sor_bloodaltar', name: 'Blood Altar', arch: 'ritualist', set: 'Cult', rarity: 'uncommon', cost: 3, type: 'persistent', atk: 0, hp: 3, text: 'Once per turn, sacrifice a creature to draw 2 cards', activated: { name: 'Sacrifice a creature: draw 2', oncePerTurn: true, cost: { sac: 1 }, actions: [{ draw: 2 }] } },
  { id: 'sor_willingsacrifice', name: 'Willing Sacrifice', arch: 'ritualist', set: 'Cult', rarity: 'uncommon', cost: 1, type: 'creature', atk: 0, hp: 1, text: 'When sacrificed, add 3 mana instead of any other sacrifice effect', sacrificed: [{ mana: 3 }] },
  { id: 'sor_cultistrally', name: 'Cultist Rally', arch: 'ritualist', set: 'Cult', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Sacrifice 2 creatures. Create a creature token with attack and health equal to their combined stats', cost2: { sac: 2 }, play: [{ token: { name: 'Amalgam', fromSacStats: true, n: 1 } }] },
  { id: 'sor_offeringtothedark', name: 'Offering to the Dark', arch: 'ritualist', set: 'Cult', rarity: 'uncommon', cost: 4, type: 'spell', text: 'Sacrifice up to 3 creatures. For each, deal 2 damage to all enemy creatures', cost2: { sacUpTo: 3 }, play: [{ t: 'allEnemy', dmg: { n: 2, per: 'sacCount' } }] },
  { id: 'sor_grandritual', name: 'Grand Ritual', arch: 'ritualist', set: 'Cult', rarity: 'uncommon', cost: 5, type: 'spell', text: 'Sacrifice 4 creatures. Draw 6 cards. Add 6 mana. Deal 6 damage to target', cost2: { sac: 4 }, play: [{ draw: 6 }, { mana: 6 }, { t: 'any', dmg: 6 }] },

  // ---- DARK RITUALIST: Pact (Uncommon) ----
  { id: 'sor_smolderingember', name: 'Smoldering Ember', arch: 'ritualist', set: 'Pact', rarity: 'uncommon', cost: 1, type: 'persistent', atk: 0, hp: 2, text: 'At start of your turn, deal damage equal to number of spells in graveyard (max 3) to target enemy creature', startTurn: [{ t: 'enemy', dmg: { per: 'graveSpells', max: 3 } }] },
  { id: 'sor_growingshadows', name: 'Growing Shadows', arch: 'ritualist', set: 'Pact', rarity: 'uncommon', cost: 2, type: 'persistent', atk: 0, hp: 2, text: 'At start of your turn, add 1 mana per 3 cards in graveyard', startTurn: [{ mana: { per: 'grave:3' } }] },
  { id: 'sor_deathcount', name: 'Death Count', arch: 'ritualist', set: 'Pact', rarity: 'uncommon', cost: 1, type: 'spell', text: 'Deal 1 damage to target. If 5+ creatures in graveyard, deal 3 instead', play: [{ t: 'any', cond: { graveCreatures: 5 }, dmg: 3, elseDmg: 1 }] },
  { id: 'sor_graveswell', name: 'Grave Swell', arch: 'ritualist', set: 'Pact', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Add 2 mana. If 8+ cards in graveyard, add 5 instead', play: [{ cond: { grave: 8 }, mana: 5, elseMana: 2 }] },
  { id: 'sor_risingdarkness', name: 'Rising Darkness', arch: 'ritualist', set: 'Pact', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Draw a card. If 6+ cards in graveyard, draw 3 instead', play: [{ cond: { grave: 6 }, draw: 3, elseDraw: 1 }] },
  { id: 'sor_pactkeeper', name: 'Pact Keeper', arch: 'ritualist', set: 'Pact', rarity: 'uncommon', cost: 3, type: 'creature', atk: 2, hp: 2, text: 'Gets +1/+1 for every 4 cards in graveyard', scaling: { a: 1, h: 1, per: 'grave:4' } },
  { id: 'sor_thresholdguardian', name: 'Threshold Guardian', arch: 'ritualist', set: 'Pact', rarity: 'uncommon', cost: 4, type: 'creature', atk: 3, hp: 3, text: 'If 10+ cards in graveyard, this has +3/+3 and Taunt', condBuff: { grave: 10, a: 3, h: 3, kw: ['taunt'] } },
  { id: 'sor_darkaccumulation', name: 'Dark Accumulation', arch: 'ritualist', set: 'Pact', rarity: 'uncommon', cost: 2, type: 'persistent', atk: 0, hp: 2, text: 'At start of your turn, if 10+ cards in graveyard, all friendly creatures get +1 attack this turn', startTurn: [{ cond: { grave: 10 }, t: 'allFriendly', buffA: 1, dur: 'turn' }] },
  { id: 'sor_inevitableend', name: 'Inevitable End', arch: 'ritualist', set: 'Pact', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Deal damage to target equal to number of creatures in graveyard (max 6)', play: [{ t: 'any', dmg: { per: 'graveCreatures', max: 6 } }] },
  { id: 'sor_sealedfate', name: 'Sealed Fate', arch: 'ritualist', set: 'Pact', rarity: 'uncommon', cost: 4, type: 'persistent', atk: 0, hp: 3, text: 'If 15+ cards in graveyard, all enemy creatures get -1/-1 at start of your turn', startTurn: [{ cond: { grave: 15 }, t: 'allEnemy', buffA: -1, buffH: -1, dur: 'perm' }] },

  // ---- DARK RITUALIST: Infernal (Rare) ----
  { id: 'sor_infernalbargain', name: 'Infernal Bargain', arch: 'ritualist', set: 'Infernal', rarity: 'rare', cost: 5, type: 'spell', text: 'Sacrifice a creature. Deal damage equal to double its attack to target', cost2: { sac: 1 }, play: [{ t: 'any', dmg: { per: 'sacAttack', mult: 2 } }] },
  { id: 'sor_demonstithe', name: "Demon's Tithe", arch: 'ritualist', set: 'Infernal', rarity: 'rare', cost: 4, type: 'spell', text: 'Sacrifice 2 creatures. Add 8 mana. Lose 3 player HP', cost2: { sac: 2, loseHP: 3 }, play: [{ mana: 8 }] },
  { id: 'sor_hellfireritual', name: 'Hellfire Ritual', arch: 'ritualist', set: 'Infernal', rarity: 'rare', cost: 6, type: 'spell', text: 'Sacrifice 3 creatures. Deal 4 damage to all enemy creatures. Lose 4 player HP', cost2: { sac: 3, loseHP: 4 }, play: [{ t: 'allEnemy', dmg: 4 }] },
  { id: 'sor_infernalsummoner', name: 'Infernal Summoner', arch: 'ritualist', set: 'Infernal', rarity: 'rare', cost: 5, type: 'creature', atk: 3, hp: 3, text: "Once per turn, sacrifice a creature. Create a Demon token with the sacrificed creature's stats +2/+2. Lose 2 player HP", activated: { name: 'Sacrifice: summon Demon', oncePerTurn: true, cost: { sac: 1, loseHP: 2 }, actions: [{ token: { name: 'Demon', fromSacStats: true, bonusA: 2, bonusH: 2, n: 1, tribe: 'Demon' } }] } },
  { id: 'sor_soulfurnace', name: 'Soul Furnace', arch: 'ritualist', set: 'Infernal', rarity: 'rare', cost: 5, type: 'persistent', atk: 0, hp: 4, text: 'Once per turn, sacrifice a creature. Add mana equal to double its cost. Lose 1 player HP', activated: { name: 'Sacrifice: double mana', oncePerTurn: true, cost: { sac: 1, loseHP: 1 }, actions: [{ mana: { per: 'sacCost', mult: 2 } }] } },
  { id: 'sor_pactwiththeabyss', name: 'Pact with the Abyss', arch: 'ritualist', set: 'Infernal', rarity: 'rare', cost: 6, type: 'spell', text: 'Sacrifice any number of creatures. For each, draw 3 cards. Lose 2 player HP per creature sacrificed', cost2: { sacUpTo: 99 }, play: [{ draw: { n: 3, per: 'sacCount' }, loseHP: { n: 2, per: 'sacCount' } }] },
  { id: 'sor_demonicconversion', name: 'Demonic Conversion', arch: 'ritualist', set: 'Infernal', rarity: 'rare', cost: 5, type: 'spell', text: "Sacrifice a creature. Create a 5/5 Demon token. Lose player HP equal to the sacrificed creature's cost", cost2: { sac: 1 }, play: [{ token: { name: 'Demon', a: 5, h: 5, n: 1, tribe: 'Demon' } }, { loseHP: { per: 'sacCost' } }] },
  { id: 'sor_bloodfountain', name: 'Blood Fountain', arch: 'ritualist', set: 'Infernal', rarity: 'rare', cost: 6, type: 'persistent', atk: 0, hp: 3, text: 'At start of your turn, sacrifice a creature. If you do, all friendly creatures get +2 attack this turn. Lose 2 player HP', manual: true },
  { id: 'sor_infernalgate', name: 'Infernal Gate', arch: 'ritualist', set: 'Infernal', rarity: 'rare', cost: 7, type: 'spell', text: 'Sacrifice 4 creatures. Create a 8/8 Demon token with Trample and Haste. Lose 5 player HP', cost2: { sac: 4, loseHP: 5 }, play: [{ token: { name: 'Greater Demon', a: 8, h: 8, n: 1, kw: ['trample', 'haste'], tribe: 'Demon' } }] },
  { id: 'sor_darkapotheosis', name: 'Dark Apotheosis', arch: 'ritualist', set: 'Infernal', rarity: 'rare', cost: 7, type: 'spell', text: "Sacrifice a creature. Target creature gains +X/+X permanently where X equals the sacrificed creature's mana cost. Lose player HP equal to X", cost2: { sac: 1 }, play: [{ t: 'creature', buffA: { per: 'sacCost' }, buffH: { per: 'sacCost' }, dur: 'perm' }, { loseHP: { per: 'sacCost' } }] },

  // ---- DARK RITUALIST: Apocalypse (Legendary) ----
  { id: 'sor_apocalypse', name: 'Apocalypse', arch: 'ritualist', set: 'Apocalypse', rarity: 'legendary', cost: 8, type: 'spell', text: 'Destroy all creatures on the board. For each friendly creature destroyed, deal 2 damage to DM HP and add 1 mana', play: [{ apocalypse: true }] },
  { id: 'sor_heraldoftheend', name: 'Herald of the End', arch: 'ritualist', set: 'Apocalypse', rarity: 'legendary', cost: 7, type: 'creature', atk: 4, hp: 4, text: 'When a friendly creature is sacrificed, deal 2 damage to all enemy creatures. When this is sacrificed, deal damage equal to the total number of creatures sacrificed this game to DM HP', sacTrigger: [{ t: 'allEnemy', dmg: 2 }], sacrificed: [{ t: 'dmface', dmg: { per: 'totalSacrificed' } }] },

  // ---- HEXER: Hex (Starter) ----
  { id: 'sor_curse', name: 'Curse', arch: 'hexer', set: 'Hex', rarity: 'starter', cost: 1, type: 'spell', text: 'Target enemy creature gets -1 attack', play: [{ t: 'enemy', buffA: -1, dur: 'perm' }] },
  { id: 'sor_weaken', name: 'Weaken', arch: 'hexer', set: 'Hex', rarity: 'starter', cost: 1, type: 'spell', text: 'Target enemy creature gets -2 health', play: [{ t: 'enemy', buffH: -2, dur: 'perm' }] },
  { id: 'sor_rot', name: 'Rot', arch: 'hexer', set: 'Hex', rarity: 'starter', cost: 2, type: 'spell', text: 'Exile a creature from graveyard. Target enemy gets -2/-2', cost2: { exile: 1, exileType: 'creature' }, play: [{ t: 'enemy', buffA: -2, buffH: -2, dur: 'perm' }] },
  { id: 'sor_blight', name: 'Blight', arch: 'hexer', set: 'Hex', rarity: 'starter', cost: 2, type: 'spell', text: 'Exile equipment from graveyard. Target enemy gets -3 attack', cost2: { exile: 1, exileType: 'equip' }, play: [{ t: 'enemy', buffA: -3, dur: 'perm' }] },
  { id: 'sor_silence', name: 'Silence', arch: 'hexer', set: 'Hex', rarity: 'starter', cost: 2, type: 'spell', text: 'Exile spell from graveyard. Target enemy loses all abilities', cost2: { exile: 1, exileType: 'spell' }, play: [{ t: 'enemy', suppress: true, dur: 'perm' }] },
  { id: 'sor_gravecurse', name: 'Grave Curse', arch: 'hexer', set: 'Hex', rarity: 'starter', cost: 3, type: 'persistent', atk: 0, hp: 2, text: 'When friendly card destroyed, target enemy gets -1/-1', allyDeath: [{ t: 'randomEnemy', buffA: -1, buffH: -1, dur: 'perm' }] },

  // ---- HEXER: Curse (Common) ----
  { id: 'sor_minorhex', name: 'Minor Hex', arch: 'hexer', set: 'Curse', rarity: 'common', cost: 1, type: 'spell', text: 'Exile a card from graveyard. Target enemy creature gets -1/-1', cost2: { exile: 1 }, play: [{ t: 'enemy', buffA: -1, buffH: -1, dur: 'perm' }] },
  { id: 'sor_enfeeble', name: 'Enfeeble', arch: 'hexer', set: 'Curse', rarity: 'common', cost: 1, type: 'spell', text: 'Exile a card from graveyard. Target enemy creature gets -2 attack', cost2: { exile: 1 }, play: [{ t: 'enemy', buffA: -2, dur: 'perm' }] },
  { id: 'sor_wither', name: 'Wither', arch: 'hexer', set: 'Curse', rarity: 'common', cost: 1, type: 'spell', text: 'Exile a card from graveyard. Target enemy creature gets -2 health', cost2: { exile: 1 }, play: [{ t: 'enemy', buffH: -2, dur: 'perm' }] },
  { id: 'sor_jinx', name: 'Jinx', arch: 'hexer', set: 'Curse', rarity: 'common', cost: 1, type: 'spell', text: 'Exile a card from graveyard. Target enemy creature loses all abilities this turn', cost2: { exile: 1 }, play: [{ t: 'enemy', suppress: true, dur: 'turn' }] },
  { id: 'sor_sapstrength', name: 'Sap Strength', arch: 'hexer', set: 'Curse', rarity: 'common', cost: 1, type: 'spell', text: 'Exile a creature from graveyard. Target enemy creature gets -1/-1 this turn', cost2: { exile: 1, exileType: 'creature' }, play: [{ t: 'enemy', buffA: -1, buffH: -1, dur: 'turn' }] },
  { id: 'sor_misfortune', name: 'Misfortune', arch: 'hexer', set: 'Curse', rarity: 'common', cost: 2, type: 'spell', text: 'Exile 2 cards from graveyard. Target enemy creature gets -2/-2', cost2: { exile: 2 }, play: [{ t: 'enemy', buffA: -2, buffH: -2, dur: 'perm' }] },
  { id: 'sor_spite', name: 'Spite', arch: 'hexer', set: 'Curse', rarity: 'common', cost: 2, type: 'spell', text: 'Exile a card from graveyard. Target enemy creature gets Poison 1', cost2: { exile: 1 }, play: [{ t: 'enemy', poison: 1 }] },
  { id: 'sor_malice', name: 'Malice', arch: 'hexer', set: 'Curse', rarity: 'common', cost: 2, type: 'spell', text: 'Exile a card from graveyard. Target enemy creature gets -1 attack this turn', cost2: { exile: 1 }, play: [{ t: 'enemy', buffA: -1, dur: 'turn' }] },
  { id: 'sor_vex', name: 'Vex', arch: 'hexer', set: 'Curse', rarity: 'common', cost: 1, type: 'spell', text: 'Exile a card from graveyard. Target enemy creature cannot use its ability next turn', cost2: { exile: 1 }, play: [{ t: 'enemy', suppress: true, dur: 1 }] },
  { id: 'sor_spreadingcurse', name: 'Spreading Curse', arch: 'hexer', set: 'Curse', rarity: 'common', cost: 2, type: 'spell', text: 'Exile 2 cards from graveyard. Up to 2 enemy creatures get -1/-1', cost2: { exile: 2 }, play: [{ t: 'enemy', n: 2, upTo: true, buffA: -1, buffH: -1, dur: 'perm' }] },

  // ---- HEXER: Blight (Uncommon) ----
  { id: 'sor_spreadingblight', name: 'Spreading Blight', arch: 'hexer', set: 'Blight', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Exile 2 cards from graveyard. All enemy creatures get -1 attack this turn', cost2: { exile: 2 }, play: [{ t: 'allEnemy', buffA: -1, dur: 'turn' }] },
  { id: 'sor_festeringwound', name: 'Festering Wound', arch: 'hexer', set: 'Blight', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Exile a creature from graveyard. Target enemy creature gets Poison 2', cost2: { exile: 1, exileType: 'creature' }, play: [{ t: 'enemy', poison: 2 }] },
  { id: 'sor_plaguewind', name: 'Plague Wind', arch: 'hexer', set: 'Blight', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Exile 3 cards from graveyard. All enemy creatures get -1/-1 this turn', cost2: { exile: 3 }, play: [{ t: 'allEnemy', buffA: -1, buffH: -1, dur: 'turn' }] },
  { id: 'sor_blightfield', name: 'Blight Field', arch: 'hexer', set: 'Blight', rarity: 'uncommon', cost: 3, type: 'persistent', atk: 0, hp: 2, text: 'At start of your turn, exile a card from graveyard. If you do, all enemy creatures get -1 attack this turn', startTurn: [{ exileCost: 1, t: 'allEnemy', buffA: -1, dur: 'turn' }] },
  { id: 'sor_decaywave', name: 'Decay Wave', arch: 'hexer', set: 'Blight', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Exile 2 cards from graveyard. All enemy creatures with 2 or less health get -1/-1 permanently', cost2: { exile: 2 }, play: [{ t: 'allEnemy', filter: 'hpMax:2', buffA: -1, buffH: -1, dur: 'perm' }] },
  { id: 'sor_witheringaura', name: 'Withering Aura', arch: 'hexer', set: 'Blight', rarity: 'uncommon', cost: 3, type: 'persistent', atk: 0, hp: 3, text: 'All enemy creatures that enter play get -1 attack while this is on the board', enemyPlayed: [{ t: 'reactionSubject', buffA: -1, dur: 'perm' }] },
  { id: 'sor_masswither', name: 'Mass Wither', arch: 'hexer', set: 'Blight', rarity: 'uncommon', cost: 4, type: 'spell', text: 'Exile 4 cards from graveyard. All enemy creatures get -2/-2 this turn', cost2: { exile: 4 }, play: [{ t: 'allEnemy', buffA: -2, buffH: -2, dur: 'turn' }] },
  { id: 'sor_corrodingmist', name: 'Corroding Mist', arch: 'hexer', set: 'Blight', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Exile a card from graveyard. All enemy equipment gets -1 to its attack bonus permanently', cost2: { exile: 1 }, manual: true },
  { id: 'sor_blightedground', name: 'Blighted Ground', arch: 'hexer', set: 'Blight', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Exile 3 cards from graveyard. All enemy creatures get Poison 1', cost2: { exile: 3 }, play: [{ t: 'allEnemy', poison: 1 }] },
  { id: 'sor_creepingrot', name: 'Creeping Rot', arch: 'hexer', set: 'Blight', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Exile a creature from graveyard. Target enemy creature gets -1/-1 permanently. If it dies this turn, another random enemy creature gets -1/-1 permanently', cost2: { exile: 1, exileType: 'creature' }, play: [{ t: 'enemy', buffA: -1, buffH: -1, dur: 'perm' }], manualNote: 'If it dies this turn, another random enemy gets -1/-1' },

  // ---- HEXER: Drain (Uncommon) ----
  { id: 'sor_soulsiphon', name: 'Soul Siphon', arch: 'hexer', set: 'Drain', rarity: 'uncommon', cost: 1, type: 'spell', text: "Exile a creature from graveyard. Add mana equal to that creature's cost (max 3)", cost2: { exile: 1, exileType: 'creature' }, play: [{ mana: { per: 'exileCost', max: 3 } }] },
  { id: 'sor_lifedrain', name: 'Life Drain', arch: 'hexer', set: 'Drain', rarity: 'uncommon', cost: 2, type: 'spell', text: "Exile a creature from graveyard. Restore player HP equal to that creature's health", cost2: { exile: 1, exileType: 'creature' }, play: [{ heal: { per: 'exileHealth' } }] },
  { id: 'sor_minddrain', name: 'Mind Drain', arch: 'hexer', set: 'Drain', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Exile 2 cards from graveyard. Draw 2 cards', cost2: { exile: 2 }, play: [{ draw: 2 }] },
  { id: 'sor_essencetheft', name: 'Essence Theft', arch: 'hexer', set: 'Drain', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Exile a creature from graveyard. Target friendly creature gets +1/+1 this turn', cost2: { exile: 1, exileType: 'creature' }, play: [{ t: 'friendly', buffA: 1, buffH: 1, dur: 'turn' }] },
  { id: 'sor_stealvitality', name: 'Steal Vitality', arch: 'hexer', set: 'Drain', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Exile a creature from graveyard. Target enemy creature gets -2/-2. Target friendly creature gets +2/+2 this turn', cost2: { exile: 1, exileType: 'creature' }, play: [{ t: 'enemy', buffA: -2, buffH: -2, dur: 'perm' }, { t: 'friendly', buffA: 2, buffH: 2, dur: 'turn' }] },
  { id: 'sor_darkharvest', name: 'Dark Harvest', arch: 'hexer', set: 'Drain', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Exile a creature from graveyard. Add 2 mana and draw a card', cost2: { exile: 1, exileType: 'creature' }, play: [{ mana: 2 }, { draw: 1 }] },
  { id: 'sor_powersiphon', name: 'Power Siphon', arch: 'hexer', set: 'Drain', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Exile 2 creatures from graveyard. Target friendly creature gets +2/+2 permanently', cost2: { exile: 2, exileType: 'creature' }, play: [{ t: 'friendly', buffA: 2, buffH: 2, dur: 'perm' }] },
  { id: 'sor_drainwell', name: 'Drain Well', arch: 'hexer', set: 'Drain', rarity: 'uncommon', cost: 3, type: 'persistent', atk: 0, hp: 2, text: 'At start of your turn, exile a card from graveyard. If you do, add 1 mana and restore 1 player HP', startTurn: [{ exileCost: 1, mana: 1, heal: 1 }] },
  { id: 'sor_soulfunnel', name: 'Soul Funnel', arch: 'hexer', set: 'Drain', rarity: 'uncommon', cost: 2, type: 'spell', text: "Exile a spell from graveyard. Add mana equal to that spell's cost", cost2: { exile: 1, exileType: 'spell' }, play: [{ mana: { per: 'exileCost' } }] },
  { id: 'sor_essenceoverload', name: 'Essence Overload', arch: 'hexer', set: 'Drain', rarity: 'uncommon', cost: 4, type: 'spell', text: 'Exile 4 cards from graveyard. Add 4 mana, draw 2 cards, restore 4 player HP', cost2: { exile: 4 }, play: [{ mana: 4 }, { draw: 2 }, { heal: 4 }] },

  // ---- HEXER: Doom (Rare) ----
  { id: 'sor_doommark', name: 'Doom Mark', arch: 'hexer', set: 'Doom', rarity: 'rare', cost: 5, type: 'spell', text: 'Exile 3 cards from graveyard. Target enemy creature gets -3/-3 permanently', cost2: { exile: 3 }, play: [{ t: 'enemy', buffA: -3, buffH: -3, dur: 'perm' }] },
  { id: 'sor_sealofruin', name: 'Seal of Ruin', arch: 'hexer', set: 'Doom', rarity: 'rare', cost: 5, type: 'spell', text: 'Exile 3 cards from graveyard. Target enemy creature loses all abilities permanently', cost2: { exile: 3 }, play: [{ t: 'enemy', suppress: true, dur: 'perm' }] },
  { id: 'sor_deathsentence', name: 'Death Sentence', arch: 'hexer', set: 'Doom', rarity: 'rare', cost: 6, type: 'spell', text: 'Exile 5 cards from graveyard. Target enemy creature gets -5/-5 permanently', cost2: { exile: 5 }, play: [{ t: 'enemy', buffA: -5, buffH: -5, dur: 'perm' }] },
  { id: 'sor_hexofunmaking', name: 'Hex of Unmaking', arch: 'hexer', set: 'Doom', rarity: 'rare', cost: 6, type: 'spell', text: 'Exile 4 cards from graveyard. Target enemy creature gets -2/-2 permanently and loses all abilities permanently', cost2: { exile: 4 }, play: [{ t: 'enemy', buffA: -2, buffH: -2, suppress: true, dur: 'perm' }] },
  { id: 'sor_doomspeaker', name: 'Doom Speaker', arch: 'hexer', set: 'Doom', rarity: 'rare', cost: 5, type: 'creature', atk: 2, hp: 4, text: 'Once per turn, exile 2 cards from graveyard. Target enemy creature gets -1/-1 permanently', activated: { name: 'Exile 2: hex enemy', oncePerTurn: true, cost: { exile: 2 }, actions: [{ t: 'enemy', buffA: -1, buffH: -1, dur: 'perm' }] } },
  { id: 'sor_annihilationcurse', name: 'Annihilation Curse', arch: 'hexer', set: 'Doom', rarity: 'rare', cost: 7, type: 'spell', text: 'Exile 6 cards from graveyard. Destroy target creature. It cannot be returned from graveyard by any means', cost2: { exile: 6 }, play: [{ t: 'enemy', destroyExile: true }] },
  { id: 'sor_spreadingdoom', name: 'Spreading Doom', arch: 'hexer', set: 'Doom', rarity: 'rare', cost: 6, type: 'spell', text: 'Exile 4 cards from graveyard. Up to 2 enemy creatures get -2/-2 permanently', cost2: { exile: 4 }, play: [{ t: 'enemy', n: 2, upTo: true, buffA: -2, buffH: -2, dur: 'perm' }] },
  { id: 'sor_doomgate', name: 'Doomgate', arch: 'hexer', set: 'Doom', rarity: 'rare', cost: 6, type: 'persistent', atk: 0, hp: 3, text: 'At start of your turn, exile 2 cards from graveyard. If you do, target enemy creature gets -1/-1 permanently', startTurn: [{ exileCost: 2, t: 'enemy', buffA: -1, buffH: -1, dur: 'perm' }] },
  { id: 'sor_unravel', name: 'Unravel', arch: 'hexer', set: 'Doom', rarity: 'rare', cost: 5, type: 'spell', text: 'Exile 3 cards from graveyard. Destroy all equipment and persistent effects attached to target enemy creature', cost2: { exile: 3 }, play: [{ t: 'enemy', destroyEquipOnVictim: true }] },
  { id: 'sor_finaldoom', name: 'Final Doom', arch: 'hexer', set: 'Doom', rarity: 'rare', cost: 7, type: 'spell', text: 'Exile 8 cards from graveyard. Target enemy creature becomes 0/1 with no abilities permanently', cost2: { exile: 8 }, play: [{ t: 'enemy', setStats: { a: 0, h: 1 }, suppress: true, dur: 'perm' }] },

  // ---- HEXER: Oblivion (Legendary) ----
  { id: 'sor_oblivion', name: 'Oblivion', arch: 'hexer', set: 'Oblivion', rarity: 'legendary', cost: 9, type: 'spell', text: 'Exile the entire graveyard. For each card exiled, all enemy creatures get -1 health. Any creature reduced to 0 health this way is destroyed and exiled', play: [{ oblivion: true }] },
  { id: 'sor_voiceofthevoid', name: 'Voice of the Void', arch: 'hexer', set: 'Oblivion', rarity: 'legendary', cost: 8, type: 'creature', atk: 3, hp: 5, text: 'Cards exiled by Hexer effects deal 1 damage to a random enemy creature when exiled. At start of your turn, exile 2 cards from graveyard', startTurn: [{ exileCost: 2, t: 'randomEnemy', dmg: 2 }], manualNote: 'Per-exile damage approximated as 2 damage on trigger' },
];
