// WIZARD — Blue. Spells, combos, triggers, multipliers.
module.exports = [
  // ---- Class Staples ----
  { id: 'wiz_counter', name: 'Counter', arch: null, set: 'Staples', rarity: 'starter', cost: 2, type: 'reaction', text: 'Reaction: Negate target spell', reaction: { on: 'spell' }, play: [{ negate: true }] },
  { id: 'wiz_insight', name: 'Insight', arch: null, set: 'Staples', rarity: 'starter', cost: 1, type: 'spell', text: 'Draw 2 cards', play: [{ draw: 2 }] },
  { id: 'wiz_arcanebolt', name: 'Arcane Bolt', arch: null, set: 'Staples', rarity: 'starter', cost: 1, type: 'spell', text: 'Deal 2 damage', play: [{ t: 'any', dmg: 2 }] },
  { id: 'wiz_dispel', name: 'Dispel', arch: null, set: 'Staples', rarity: 'starter', cost: 1, type: 'reaction', text: 'Reaction: Destroy target equipment or persistent effect', reaction: { on: 'any' }, play: [{ destroyT: { filter: 'equip,persistent', n: 1 } }] },

  // ---- ENCHANTER: Starter ----
  { id: 'wiz_quicken', name: 'Quicken', arch: 'enchanter', set: 'Starter', rarity: 'starter', cost: 1, type: 'spell', text: 'Target creature gains Haste this turn', play: [{ t: 'creature', kw: ['haste'], dur: 'turn' }] },
  { id: 'wiz_sharpen', name: 'Sharpen', arch: 'enchanter', set: 'Starter', rarity: 'starter', cost: 1, type: 'spell', text: 'Target creature gains First Strike this turn', play: [{ t: 'creature', kw: ['firststrike'], dur: 'turn' }] },
  { id: 'wiz_venomtip', name: 'Venomtip', arch: 'enchanter', set: 'Starter', rarity: 'starter', cost: 2, type: 'spell', text: 'Target creature gains Deathtouch this turn', play: [{ t: 'creature', kw: ['deathtouch'], dur: 'turn' }] },
  { id: 'wiz_lifebound', name: 'Lifebound', arch: 'enchanter', set: 'Starter', rarity: 'starter', cost: 2, type: 'spell', text: 'Target creature gains Lifelink this turn', play: [{ t: 'creature', kw: ['lifelink'], dur: 'turn' }] },
  { id: 'wiz_fortify', name: 'Fortify', arch: 'enchanter', set: 'Starter', rarity: 'starter', cost: 1, type: 'spell', text: 'Target creature gains Taunt this turn', play: [{ t: 'creature', kw: ['taunt'], dur: 'turn' }] },
  { id: 'wiz_tramplehex', name: 'Trample Hex', arch: 'enchanter', set: 'Starter', rarity: 'starter', cost: 2, type: 'spell', text: 'Target creature gains Trample this turn', play: [{ t: 'creature', kw: ['trample'], dur: 'turn' }] },
  { id: 'wiz_dualenchant', name: 'Dual Enchant', arch: 'enchanter', set: 'Starter', rarity: 'starter', cost: 2, type: 'spell', text: 'Target creature gains two keywords of your choice from: Haste, First Strike, Trample, Taunt this turn', play: [{ t: 'creature', kwPick: { from: ['haste', 'firststrike', 'trample', 'taunt'], n: 2 }, dur: 'turn' }] },

  // ---- ENCHANTER: Fire (Common) ----
  { id: 'wiz_ignite', name: 'Ignite', arch: 'enchanter', set: 'Fire', rarity: 'common', cost: 1, type: 'spell', text: 'Target creature gains Trample this turn', play: [{ t: 'creature', kw: ['trample'], dur: 'turn' }] },
  { id: 'wiz_flametongue', name: 'Flame Tongue', arch: 'enchanter', set: 'Fire', rarity: 'common', cost: 1, type: 'spell', text: 'Target creature gains "deal 1 damage to another enemy target when this attacks" this turn', manual: true },
  { id: 'wiz_searingbrand', name: 'Searing Brand', arch: 'enchanter', set: 'Fire', rarity: 'common', cost: 1, type: 'spell', text: 'Target creature gains Deathtouch this turn', play: [{ t: 'creature', kw: ['deathtouch'], dur: 'turn' }] },
  { id: 'wiz_blazingcharge', name: 'Blazing Charge', arch: 'enchanter', set: 'Fire', rarity: 'common', cost: 2, type: 'spell', text: 'Target creature gains Haste this turn', play: [{ t: 'creature', kw: ['haste'], dur: 'turn' }] },
  { id: 'wiz_fireshield', name: 'Fire Shield', arch: 'enchanter', set: 'Fire', rarity: 'common', cost: 1, type: 'spell', text: 'Target creature gains "when attacked, deal 2 damage to the attacker" this turn', play: [{ t: 'creature', kw: ['retaliate:2'], dur: 'turn' }] },
  { id: 'wiz_combustion', name: 'Combustion', arch: 'enchanter', set: 'Fire', rarity: 'common', cost: 2, type: 'spell', text: 'Target creature gains Trample and First Strike this turn', play: [{ t: 'creature', kw: ['trample', 'firststrike'], dur: 'turn' }] },
  { id: 'wiz_infernomark', name: 'Inferno Mark', arch: 'enchanter', set: 'Fire', rarity: 'common', cost: 2, type: 'spell', text: 'Target creature gains "deal 1 damage to all enemy creatures when this attacks" this turn', manual: true },
  { id: 'wiz_wildfirebrand', name: 'Wildfire Brand', arch: 'enchanter', set: 'Fire', rarity: 'common', cost: 2, type: 'spell', text: 'Target creature gains "when this kills a creature, deal 2 damage to another random enemy creature" this turn', manual: true },
  { id: 'wiz_scorchenchant', name: 'Scorch Enchant', arch: 'enchanter', set: 'Fire', rarity: 'common', cost: 1, type: 'spell', text: 'Target creature gains First Strike this turn. If it already has First Strike, it gains Deathtouch instead', play: [{ t: 'creature', kwUpgrade: { has: 'firststrike', then: 'deathtouch', else: 'firststrike' }, dur: 'turn' }] },
  { id: 'wiz_pyroclasm', name: 'Pyroclasm', arch: 'enchanter', set: 'Fire', rarity: 'common', cost: 3, type: 'spell', text: 'All friendly creatures gain Trample this turn', play: [{ t: 'allFriendly', kw: ['trample'], dur: 'turn' }] },

  // ---- ENCHANTER: Storm (Common) ----
  { id: 'wiz_tempesttouch', name: 'Tempest Touch', arch: 'enchanter', set: 'Storm', rarity: 'common', cost: 1, type: 'spell', text: 'Target creature gains First Strike and Trample this turn', play: [{ t: 'creature', kw: ['firststrike', 'trample'], dur: 'turn' }] },
  { id: 'wiz_stormsurge', name: 'Storm Surge', arch: 'enchanter', set: 'Storm', rarity: 'common', cost: 2, type: 'spell', text: 'Target creature gains Haste and Lifelink this turn', play: [{ t: 'creature', kw: ['haste', 'lifelink'], dur: 'turn' }] },
  { id: 'wiz_galebrand', name: 'Gale Brand', arch: 'enchanter', set: 'Storm', rarity: 'common', cost: 1, type: 'spell', text: 'Target creature gains Taunt and First Strike this turn', play: [{ t: 'creature', kw: ['taunt', 'firststrike'], dur: 'turn' }] },
  { id: 'wiz_thundermark', name: 'Thunder Mark', arch: 'enchanter', set: 'Storm', rarity: 'common', cost: 2, type: 'spell', text: 'Target creature gains Haste and Deathtouch this turn', play: [{ t: 'creature', kw: ['haste', 'deathtouch'], dur: 'turn' }] },
  { id: 'wiz_squallline', name: 'Squall Line', arch: 'enchanter', set: 'Storm', rarity: 'common', cost: 2, type: 'spell', text: 'Up to 2 creatures each gain Trample this turn', play: [{ t: 'creature', n: 2, upTo: true, kw: ['trample'], dur: 'turn' }] },
  { id: 'wiz_windborne', name: 'Windborne', arch: 'enchanter', set: 'Storm', rarity: 'common', cost: 1, type: 'spell', text: 'Target creature gains Lifelink and First Strike this turn', play: [{ t: 'creature', kw: ['lifelink', 'firststrike'], dur: 'turn' }] },
  { id: 'wiz_lightningrod', name: 'Lightning Rod', arch: 'enchanter', set: 'Storm', rarity: 'common', cost: 2, type: 'spell', text: 'Target creature gains Taunt and "deal 1 damage to each creature that attacks this" this turn', play: [{ t: 'creature', kw: ['taunt', 'retaliate:1'], dur: 'turn' }] },
  { id: 'wiz_eyeofthestorm', name: 'Eye of the Storm', arch: 'enchanter', set: 'Storm', rarity: 'common', cost: 2, type: 'spell', text: 'Target creature gains Haste, First Strike, and Trample this turn', play: [{ t: 'creature', kw: ['haste', 'firststrike', 'trample'], dur: 'turn' }] },
  { id: 'wiz_howlingwind', name: 'Howling Wind', arch: 'enchanter', set: 'Storm', rarity: 'common', cost: 2, type: 'spell', text: 'All friendly creatures gain First Strike this turn', play: [{ t: 'allFriendly', kw: ['firststrike'], dur: 'turn' }] },
  { id: 'wiz_maelstrom', name: 'Maelstrom', arch: 'enchanter', set: 'Storm', rarity: 'common', cost: 3, type: 'spell', text: 'All friendly creatures gain Trample and First Strike this turn', play: [{ t: 'allFriendly', kw: ['trample', 'firststrike'], dur: 'turn' }] },

  // ---- ENCHANTER: Lightning (Uncommon) ----
  { id: 'wiz_staticcharge', name: 'Static Charge', arch: 'enchanter', set: 'Lightning', rarity: 'uncommon', cost: 1, type: 'reaction', text: 'Reaction: When a friendly creature is attacked, it gains First Strike for this combat', reaction: { on: 'attack' }, play: [{ t: 'reactionSubject', kw: ['firststrike'], dur: 'turn' }] },
  { id: 'wiz_galvanize', name: 'Galvanize', arch: 'enchanter', set: 'Lightning', rarity: 'uncommon', cost: 1, type: 'reaction', text: 'Reaction: When a friendly creature enters play, it gains Haste this turn', reaction: { on: 'creaturePlayed' }, play: [{ t: 'reactionSubject', kw: ['haste'], dur: 'turn' }] },
  { id: 'wiz_thunderclap', name: 'Thunderclap', arch: 'enchanter', set: 'Lightning', rarity: 'uncommon', cost: 2, type: 'reaction', text: 'Reaction: When DM plays a creature, target friendly creature gains Deathtouch this turn', reaction: { on: 'creaturePlayed' }, play: [{ t: 'friendly', kw: ['deathtouch'], dur: 'turn' }] },
  { id: 'wiz_chainlightning', name: 'Chain Lightning', arch: 'enchanter', set: 'Lightning', rarity: 'uncommon', cost: 2, type: 'reaction', text: 'Reaction: When a friendly creature kills an enemy, it gains Haste this turn', reaction: { on: 'kill' }, play: [{ t: 'reactionSubject', kw: ['haste'], dur: 'turn' }] },
  { id: 'wiz_overcharge', name: 'Overcharge', arch: 'enchanter', set: 'Lightning', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Target creature gains Haste and Trample this turn. Deal 1 damage to it at end of turn', play: [{ t: 'creature', kw: ['haste', 'trample'], dur: 'turn', scheduleSelf: { when: 'endTurn', dmg: 1 } }] },
  { id: 'wiz_arc', name: 'Arc', arch: 'enchanter', set: 'Lightning', rarity: 'uncommon', cost: 1, type: 'reaction', text: 'Reaction: When a friendly creature attacks, it gains Trample for this attack', reaction: { on: 'attack' }, play: [{ t: 'reactionSubject', kw: ['trample'], dur: 'turn' }] },
  { id: 'wiz_jolt', name: 'Jolt', arch: 'enchanter', set: 'Lightning', rarity: 'uncommon', cost: 1, type: 'reaction', text: 'Reaction: When a friendly creature attacks, it gains First Strike for this attack', reaction: { on: 'attack' }, play: [{ t: 'reactionSubject', kw: ['firststrike'], dur: 'turn' }] },
  { id: 'wiz_conductor', name: 'Conductor', arch: 'enchanter', set: 'Lightning', rarity: 'uncommon', cost: 2, type: 'reaction', text: 'Reaction: When a friendly creature with a keyword kills an enemy creature, give that keyword to another friendly creature this turn', reaction: { on: 'kill' }, manual: true },
  { id: 'wiz_balllightning', name: 'Ball Lightning', arch: 'enchanter', set: 'Lightning', rarity: 'uncommon', cost: 2, type: 'reaction', text: 'Reaction: Target creature gains Deathtouch and First Strike this turn. Destroy it at end of turn', reaction: { on: 'any' }, play: [{ t: 'creature', kw: ['deathtouch', 'firststrike'], dur: 'turn', scheduleSelf: { when: 'endTurn', destroy: true } }] },
  { id: 'wiz_stormstrike', name: 'Storm Strike', arch: 'enchanter', set: 'Lightning', rarity: 'uncommon', cost: 3, type: 'reaction', text: 'Reaction: When a friendly creature attacks, it gains First Strike, Trample, and Deathtouch for this attack. Deal 2 damage to it after combat', reaction: { on: 'attack' }, play: [{ t: 'reactionSubject', kw: ['firststrike', 'trample', 'deathtouch'], dur: 'turn', scheduleSelf: { when: 'endTurn', dmg: 2 } }] },

  // ---- ENCHANTER: Frost (Uncommon) ----
  { id: 'wiz_freeze', name: 'Freeze', arch: 'enchanter', set: 'Frost', rarity: 'uncommon', cost: 1, type: 'spell', text: 'Target enemy creature cannot attack this turn', play: [{ t: 'enemy', cantAttack: 1 }] },
  { id: 'wiz_frostbite', name: 'Frostbite', arch: 'enchanter', set: 'Frost', rarity: 'uncommon', cost: 1, type: 'spell', text: 'Target enemy creature loses all keywords this turn', play: [{ t: 'enemy', removeKw: 'all', dur: 'turn' }] },
  { id: 'wiz_icechains', name: 'Ice Chains', arch: 'enchanter', set: 'Frost', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Target enemy creature cannot attack for 2 turns', play: [{ t: 'enemy', cantAttack: 2 }] },
  { id: 'wiz_flashfreeze', name: 'Flash Freeze', arch: 'enchanter', set: 'Frost', rarity: 'uncommon', cost: 1, type: 'reaction', text: 'Reaction: When an enemy creature gains a keyword or buff, negate it', reaction: { on: 'any' }, manual: true },
  { id: 'wiz_bittercold', name: 'Bitter Cold', arch: 'enchanter', set: 'Frost', rarity: 'uncommon', cost: 2, type: 'spell', text: 'All enemy creatures lose Haste this turn', play: [{ t: 'allEnemy', removeKw: ['haste'], dur: 'turn' }] },
  { id: 'wiz_glacialpace', name: 'Glacial Pace', arch: 'enchanter', set: 'Frost', rarity: 'uncommon', cost: 2, type: 'reaction', text: "Reaction: When DM plays a creature, it cannot attack until DM's next turn", reaction: { on: 'creaturePlayed' }, play: [{ t: 'reactionSubject', cantAttack: 1 }] },
  { id: 'wiz_frozensolid', name: 'Frozen Solid', arch: 'enchanter', set: 'Frost', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Target enemy creature cannot attack or use abilities this turn', play: [{ t: 'enemy', cantAttack: 1, suppress: true, dur: 'turn' }] },
  { id: 'wiz_numbingcold', name: 'Numbing Cold', arch: 'enchanter', set: 'Frost', rarity: 'uncommon', cost: 1, type: 'spell', text: 'Target enemy creature loses First Strike and Deathtouch this turn', play: [{ t: 'enemy', removeKw: ['firststrike', 'deathtouch'], dur: 'turn' }] },
  { id: 'wiz_permafrost', name: 'Permafrost', arch: 'enchanter', set: 'Frost', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Target enemy creature cannot attack for 3 turns', play: [{ t: 'enemy', cantAttack: 3 }] },
  { id: 'wiz_absolutezero', name: 'Absolute Zero', arch: 'enchanter', set: 'Frost', rarity: 'uncommon', cost: 3, type: 'spell', text: 'All enemy creatures lose all keywords and cannot attack this turn', play: [{ t: 'allEnemy', removeKw: 'all', cantAttack: 1, dur: 'turn' }] },

  // ---- ENCHANTER: Earth (Rare) ----
  { id: 'wiz_stoneskinenchant', name: 'Stoneskin Enchant', arch: 'enchanter', set: 'Earth', rarity: 'rare', cost: 3, type: 'spell', text: 'Target creature gains Taunt permanently', play: [{ t: 'creature', kw: ['taunt'], dur: 'perm' }] },
  { id: 'wiz_ironhide', name: 'Ironhide', arch: 'enchanter', set: 'Earth', rarity: 'rare', cost: 3, type: 'spell', text: 'Target creature gains First Strike permanently', play: [{ t: 'creature', kw: ['firststrike'], dur: 'perm' }] },
  { id: 'wiz_earthenmight', name: 'Earthen Might', arch: 'enchanter', set: 'Earth', rarity: 'rare', cost: 4, type: 'spell', text: 'Target creature gains Trample permanently', play: [{ t: 'creature', kw: ['trample'], dur: 'perm' }] },
  { id: 'wiz_rootbound', name: 'Rootbound', arch: 'enchanter', set: 'Earth', rarity: 'rare', cost: 3, type: 'spell', text: 'Target creature gains Lifelink permanently', play: [{ t: 'creature', kw: ['lifelink'], dur: 'perm' }] },
  { id: 'wiz_bedrockenchant', name: 'Bedrock Enchant', arch: 'enchanter', set: 'Earth', rarity: 'rare', cost: 4, type: 'spell', text: 'Target creature gains Taunt and First Strike permanently', play: [{ t: 'creature', kw: ['taunt', 'firststrike'], dur: 'perm' }] },
  { id: 'wiz_mountainsheart', name: "Mountain's Heart", arch: 'enchanter', set: 'Earth', rarity: 'rare', cost: 4, type: 'spell', text: 'Target creature gains Trample and Lifelink permanently', play: [{ t: 'creature', kw: ['trample', 'lifelink'], dur: 'perm' }] },
  { id: 'wiz_fossilize', name: 'Fossilize', arch: 'enchanter', set: 'Earth', rarity: 'rare', cost: 3, type: 'spell', text: 'Target creature gains Deathtouch permanently. It cannot gain Haste', play: [{ t: 'creature', kw: ['deathtouch'], dur: 'perm', note: 'Cannot gain Haste' }] },
  { id: 'wiz_tectonicbrand', name: 'Tectonic Brand', arch: 'enchanter', set: 'Earth', rarity: 'rare', cost: 5, type: 'spell', text: 'Target creature gains Trample, First Strike, and Taunt permanently', play: [{ t: 'creature', kw: ['trample', 'firststrike', 'taunt'], dur: 'perm' }] },
  { id: 'wiz_livingstone', name: 'Living Stone', arch: 'enchanter', set: 'Earth', rarity: 'rare', cost: 4, type: 'spell', text: 'Target creature gains "this creature\'s keywords cannot be removed" permanently', play: [{ t: 'creature', kw: ['kwlock'], dur: 'perm' }] },
  { id: 'wiz_worldanchor', name: 'World Anchor', arch: 'enchanter', set: 'Earth', rarity: 'rare', cost: 6, type: 'persistent', atk: 0, hp: 4, text: 'Persistent. All keywords on friendly creatures cannot be removed or negated', manualNote: 'Keyword protection enforced while on board' },

  // ---- ENCHANTER: Void (Legendary) ----
  { id: 'wiz_voidenchant', name: 'Void Enchant', arch: 'enchanter', set: 'Void', rarity: 'legendary', cost: 8, type: 'spell', text: 'Target creature gains "creatures killed by this are exiled instead of going to the graveyard" and "this creature\'s keywords cannot be removed" permanently', play: [{ t: 'creature', kw: ['kwlock', 'voidtouch'], dur: 'perm' }] },
  { id: 'wiz_entropy', name: 'Entropy', arch: 'enchanter', set: 'Void', rarity: 'legendary', cost: 6, type: 'spell', text: 'All enemy creatures lose all keywords and all abilities permanently', play: [{ t: 'allEnemy', removeKw: 'all', suppress: true, dur: 'perm' }] },

  // ---- ILLUSIONIST: Starter ----
  { id: 'wiz_mirrorimage', name: 'Mirror Image', arch: 'illusionist', set: 'Starter', rarity: 'starter', cost: 1, type: 'spell', text: 'Create a 1/1 copy of target creature (no abilities)', play: [{ t: 'creature', copyC: { mode: 'oneone' } }] },
  { id: 'wiz_echo', name: 'Echo', arch: 'illusionist', set: 'Starter', rarity: 'starter', cost: 2, type: 'spell', text: 'Copy target spell you just played', manual: true },
  { id: 'wiz_duplicate', name: 'Duplicate', arch: 'illusionist', set: 'Starter', rarity: 'starter', cost: 2, type: 'spell', text: 'Create a copy of target creature with cost 2 or less', play: [{ t: 'creature', filter: 'costMax:2', copyC: { mode: 'full' } }] },
  { id: 'wiz_phantomdouble', name: 'Phantom Double', arch: 'illusionist', set: 'Starter', rarity: 'starter', cost: 3, type: 'spell', text: 'Create a copy of target creature. Destroy it at end of turn', play: [{ t: 'creature', copyC: { mode: 'full', temp: true } }] },
  { id: 'wiz_split', name: 'Split', arch: 'illusionist', set: 'Starter', rarity: 'starter', cost: 3, type: 'spell', text: 'Target creature becomes two with half stats (rounded down)', play: [{ t: 'creature', split: { round: 'down' } }] },
  { id: 'wiz_miragearmy', name: 'Mirage Army', arch: 'illusionist', set: 'Starter', rarity: 'starter', cost: 4, type: 'spell', text: 'Create 1/1 copies of up to 3 creatures (no abilities)', play: [{ t: 'creature', n: 3, upTo: true, copyC: { mode: 'oneone' } }] },

  // ---- ILLUSIONIST: Shadow (Common) ----
  { id: 'wiz_shadowclone', name: 'Shadow Clone', arch: 'illusionist', set: 'Shadow', rarity: 'common', cost: 1, type: 'spell', text: 'Create a 1/1 copy of target creature (no abilities). Destroy it at end of turn', play: [{ t: 'creature', copyC: { mode: 'oneone', temp: true } }] },
  { id: 'wiz_darkreflection', name: 'Dark Reflection', arch: 'illusionist', set: 'Shadow', rarity: 'common', cost: 2, type: 'spell', text: 'Create a copy of target creature with cost 2 or less. It has -1 health', play: [{ t: 'creature', filter: 'costMax:2', copyC: { mode: 'full', hMinus: 1 } }] },
  { id: 'wiz_shade', name: 'Shade', arch: 'illusionist', set: 'Shadow', rarity: 'common', cost: 1, type: 'spell', text: 'Create a 1/1 Shadow token. When it dies, deal 1 damage to any target', play: [{ token: { name: 'Shadow', a: 1, h: 1, n: 1, tribe: 'Shadow', deathDmg: 1 } }] },
  { id: 'wiz_shadowstep', name: 'Shadow Step', arch: 'illusionist', set: 'Shadow', rarity: 'common', cost: 1, type: 'spell', text: 'Target creature cannot be targeted by attacks this turn', play: [{ t: 'creature', kw: ['noattack'], dur: 'turn' }] },
  { id: 'wiz_umbralecho', name: 'Umbral Echo', arch: 'illusionist', set: 'Shadow', rarity: 'common', cost: 2, type: 'spell', text: 'Copy target spell you just played. The copy deals 1 less damage or gives 1 less buff', manual: true },
  { id: 'wiz_shadowpuppet', name: 'Shadow Puppet', arch: 'illusionist', set: 'Shadow', rarity: 'common', cost: 2, type: 'spell', text: 'Create a 1/1 copy of target enemy creature (no abilities) under your control', play: [{ t: 'enemy', copyC: { mode: 'oneone' } }] },
  { id: 'wiz_creepingdarkness', name: 'Creeping Darkness', arch: 'illusionist', set: 'Shadow', rarity: 'common', cost: 1, type: 'spell', text: 'Target enemy creature gets -1 attack this turn. Create a 1/1 Shadow token', play: [{ t: 'enemy', buffA: -1, dur: 'turn' }, { token: { name: 'Shadow', a: 1, h: 1, n: 1, tribe: 'Shadow' } }] },
  { id: 'wiz_duskveil', name: 'Dusk Veil', arch: 'illusionist', set: 'Shadow', rarity: 'common', cost: 1, type: 'spell', text: 'Target creature cannot be targeted by spells this turn', play: [{ t: 'creature', kw: ['nospell'], dur: 'turn' }] },
  { id: 'wiz_shadowarmy', name: 'Shadow Army', arch: 'illusionist', set: 'Shadow', rarity: 'common', cost: 3, type: 'spell', text: 'Create 1/1 Shadow copies of up to 2 friendly creatures (no abilities). Destroy them at end of turn', play: [{ t: 'friendly', n: 2, upTo: true, copyC: { mode: 'oneone', temp: true } }] },
  { id: 'wiz_eclipse', name: 'Eclipse', arch: 'illusionist', set: 'Shadow', rarity: 'common', cost: 2, type: 'spell', text: 'All enemy creatures get -1 attack this turn. Create a 1/1 Shadow token for each enemy creature', play: [{ t: 'allEnemy', buffA: -1, dur: 'turn' }, { token: { name: 'Shadow', a: 1, h: 1, n: { per: 'enemyCreatures' }, tribe: 'Shadow' } }] },

  // ---- ILLUSIONIST: Mimic (Uncommon) ----
  { id: 'wiz_copycat', name: 'Copycat', arch: 'illusionist', set: 'Mimic', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Create a 1/1 copy of target enemy creature (no abilities) under your control', play: [{ t: 'enemy', copyC: { mode: 'oneone' } }] },
  { id: 'wiz_mimicform', name: 'Mimic Form', arch: 'illusionist', set: 'Mimic', rarity: 'uncommon', cost: 2, type: 'reaction', text: 'Reaction: When DM plays a creature, create a 1/1 copy of it under your control', reaction: { on: 'creaturePlayed' }, play: [{ t: 'reactionSubject', copyC: { mode: 'oneone' } }] },
  { id: 'wiz_stealspell', name: 'Steal Spell', arch: 'illusionist', set: 'Mimic', rarity: 'uncommon', cost: 2, type: 'reaction', text: 'Reaction: When DM casts a spell, copy it. You choose the new targets', reaction: { on: 'spell' }, manual: true },
  { id: 'wiz_absorbidentity', name: 'Absorb Identity', arch: 'illusionist', set: 'Mimic', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Target friendly creature becomes a copy of target enemy creature. Same stats, same abilities', manual: true },
  { id: 'wiz_doppelganger', name: 'Doppelganger', arch: 'illusionist', set: 'Mimic', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Create a copy of target enemy creature with full stats and abilities. Destroy it at end of turn', play: [{ t: 'enemy', copyC: { mode: 'full', temp: true } }] },
  { id: 'wiz_impostor', name: 'Impostor', arch: 'illusionist', set: 'Mimic', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Create a copy of target enemy creature with cost 3 or less. Full abilities', play: [{ t: 'enemy', filter: 'costMax:3', copyC: { mode: 'full' } }] },
  { id: 'wiz_turncoat', name: 'Turncoat', arch: 'illusionist', set: 'Mimic', rarity: 'uncommon', cost: 1, type: 'reaction', text: 'Reaction: When an enemy creature attacks, create a 1/1 copy of it that blocks the attack', reaction: { on: 'attack' }, manual: true },
  { id: 'wiz_adaptiveclone', name: 'Adaptive Clone', arch: 'illusionist', set: 'Mimic', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Create a copy of target creature that just died this turn under your control. Half stats, full abilities', manual: true },
  { id: 'wiz_mirrormatch', name: 'Mirror Match', arch: 'illusionist', set: 'Mimic', rarity: 'uncommon', cost: 3, type: 'reaction', text: 'Reaction: When DM plays a creature with cost 4+, create a copy of it under your control with half stats', reaction: { on: 'creaturePlayed' }, play: [{ t: 'reactionSubject', copyC: { mode: 'half' } }] },
  { id: 'wiz_identitytheft', name: 'Identity Theft', arch: 'illusionist', set: 'Mimic', rarity: 'uncommon', cost: 4, type: 'spell', text: 'Take control of target enemy creature until end of turn. It gains Haste', manual: true },

  // ---- ILLUSIONIST: Phantasm (Uncommon) ----
  { id: 'wiz_decoy', name: 'Decoy', arch: 'illusionist', set: 'Phantasm', rarity: 'uncommon', cost: 1, type: 'spell', text: 'Create a 0/1 Phantasm token with Taunt. When it takes any damage, destroy it', play: [{ token: { name: 'Phantasm', a: 0, h: 1, n: 1, kw: ['taunt', 'fragile'], tribe: 'Phantasm' } }] },
  { id: 'wiz_falsearmy', name: 'False Army', arch: 'illusionist', set: 'Phantasm', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Create three 0/1 Phantasm tokens with Taunt. When they take any damage, destroy them', play: [{ token: { name: 'Phantasm', a: 0, h: 1, n: 3, kw: ['taunt', 'fragile'], tribe: 'Phantasm' } }] },
  { id: 'wiz_illusorygiant', name: 'Illusory Giant', arch: 'illusionist', set: 'Phantasm', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Create a 5/1 Phantasm creature. When it takes any damage, destroy it', play: [{ token: { name: 'Illusory Giant', a: 5, h: 1, n: 1, kw: ['fragile'], tribe: 'Phantasm' } }] },
  { id: 'wiz_phantomthreat', name: 'Phantom Threat', arch: 'illusionist', set: 'Phantasm', rarity: 'uncommon', cost: 1, type: 'reaction', text: 'Reaction: When DM declares an attack on a friendly creature, redirect it to a 0/1 Phantasm token that is destroyed on hit', reaction: { on: 'attack' }, manual: true },
  { id: 'wiz_veilofillusions', name: 'Veil of Illusions', arch: 'illusionist', set: 'Phantasm', rarity: 'uncommon', cost: 2, type: 'reaction', text: 'Reaction: When a friendly creature would take lethal damage, replace it with a 0/1 Phantasm token. Return the original to your hand', reaction: { on: 'wouldDie' }, manual: true },
  { id: 'wiz_baitandswitch', name: 'Bait and Switch', arch: 'illusionist', set: 'Phantasm', rarity: 'uncommon', cost: 1, type: 'spell', text: "Create a 0/1 Phantasm token with Taunt. Return target friendly creature to its owner's hand", play: [{ token: { name: 'Phantasm', a: 0, h: 1, n: 1, kw: ['taunt', 'fragile'], tribe: 'Phantasm' } }, { bounce: { t: 'friendly', n: 1 } }] },
  { id: 'wiz_phantasmalarmor', name: 'Phantasmal Armor', arch: 'illusionist', set: 'Phantasm', rarity: 'uncommon', cost: 1, type: 'spell', text: 'Target creature gains +3 health. If this creature is targeted by a spell, remove the bonus instead', play: [{ t: 'creature', buffH: 3, dur: 'perm', note: 'Remove bonus if targeted by a spell' }] },
  { id: 'wiz_frightfulpresence', name: 'Frightful Presence', arch: 'illusionist', set: 'Phantasm', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Create a 4/1 Phantasm creature with Taunt. When it takes any damage, destroy it', play: [{ token: { name: 'Frightful Phantasm', a: 4, h: 1, n: 1, kw: ['taunt', 'fragile'], tribe: 'Phantasm' } }] },
  { id: 'wiz_smokeandmirrors', name: 'Smoke and Mirrors', arch: 'illusionist', set: 'Phantasm', rarity: 'uncommon', cost: 2, type: 'reaction', text: 'Reaction: Negate target spell. Create a 0/1 Phantasm token', reaction: { on: 'spell' }, play: [{ negate: true }, { token: { name: 'Phantasm', a: 0, h: 1, n: 1, kw: ['fragile'], tribe: 'Phantasm' } }] },
  { id: 'wiz_masshallucination', name: 'Mass Hallucination', arch: 'illusionist', set: 'Phantasm', rarity: 'uncommon', cost: 3, type: 'spell', text: 'All enemy creatures attack random targets this turn instead of chosen targets', manual: true },

  // ---- ILLUSIONIST: Dream (Rare) ----
  { id: 'wiz_lucidcopy', name: 'Lucid Copy', arch: 'illusionist', set: 'Dream', rarity: 'rare', cost: 5, type: 'spell', text: 'Create a copy of any creature in any graveyard with full stats and abilities', play: [{ copyC: { mode: 'full', src: 'grave' } }] },
  { id: 'wiz_dreamwalk', name: 'Dream Walk', arch: 'illusionist', set: 'Dream', rarity: 'rare', cost: 4, type: 'reaction', text: 'Reaction: When a friendly creature would die, create a copy of it with 1 health. It enters play at start of your next turn', reaction: { on: 'wouldDie' }, manual: true },
  { id: 'wiz_nightmare', name: 'Nightmare', arch: 'illusionist', set: 'Dream', rarity: 'rare', cost: 5, type: 'spell', text: "Create a copy of the strongest creature on the DM's board. It has Haste. Destroy it at end of turn", play: [{ copyC: { mode: 'full', src: 'strongestEnemy', temp: true, kw: ['haste'] } }] },
  { id: 'wiz_sleeperagent', name: 'Sleeper Agent', arch: 'illusionist', set: 'Dream', rarity: 'rare', cost: 4, type: 'spell', text: "Look at the top 5 cards of the DM's deck. Create a copy of a creature found there with half stats", manual: true },
  { id: 'wiz_wakingdream', name: 'Waking Dream', arch: 'illusionist', set: 'Dream', rarity: 'rare', cost: 6, type: 'spell', text: 'Create copies of up to 2 friendly creatures with full stats and abilities. Destroy them at end of your next turn', play: [{ t: 'friendly', n: 2, upTo: true, copyC: { mode: 'full', tempTurns: 2 } }] },
  { id: 'wiz_dreameater', name: 'Dream Eater', arch: 'illusionist', set: 'Dream', rarity: 'rare', cost: 5, type: 'reaction', text: 'Reaction: When DM plays a creature, create a copy of it under your control. Destroy whichever copy has less health at end of turn', reaction: { on: 'creaturePlayed' }, manual: true },
  { id: 'wiz_recurringnightmare', name: 'Recurring Nightmare', arch: 'illusionist', set: 'Dream', rarity: 'rare', cost: 5, type: 'persistent', atk: 0, hp: 3, text: 'Persistent. At start of your turn, create a 1/1 copy of a random creature in any graveyard (no abilities)', startTurn: [{ copyC: { mode: 'oneone', src: 'randomGrave' } }] },
  { id: 'wiz_shareddream', name: 'Shared Dream', arch: 'illusionist', set: 'Dream', rarity: 'rare', cost: 4, type: 'spell', text: "Target ally draws a card. Create a copy of a creature in that ally's hand with half stats. Destroy it at end of turn", manual: true },
  { id: 'wiz_figment', name: 'Figment', arch: 'illusionist', set: 'Dream', rarity: 'rare', cost: 3, type: 'reaction', text: 'Reaction: When a friendly illusion or copy is destroyed, create a 1/1 copy of it', reaction: { on: 'allyDeath' }, manual: true },
  { id: 'wiz_dreamscape', name: 'Dreamscape', arch: 'illusionist', set: 'Dream', rarity: 'rare', cost: 7, type: 'persistent', atk: 0, hp: 4, text: "Persistent. All copies and illusions you create gain +1/+1 and don't expire at end of turn", manualNote: 'Applies to new copies while on board' },

  // ---- ILLUSIONIST: Perfect (Legendary) ----
  { id: 'wiz_perfectillusion', name: 'Perfect Illusion', arch: 'illusionist', set: 'Perfect', rarity: 'legendary', cost: 8, type: 'spell', text: 'Create a permanent copy of any creature on the board or in any graveyard. Full stats, full abilities. This copy cannot be dispelled or exiled. It is real', play: [{ copyC: { mode: 'full', src: 'anywhere' } }] },
  { id: 'wiz_rewritereality', name: 'Rewrite Reality', arch: 'illusionist', set: 'Perfect', rarity: 'legendary', cost: 7, type: 'spell', text: 'Target friendly creature becomes an exact copy of any creature on the board. Permanent. It retains all equipment', manual: true },

  // ---- ABJURER: Starter ----
  { id: 'wiz_nullify', name: 'Nullify', arch: 'abjurer', set: 'Starter', rarity: 'starter', cost: 1, type: 'reaction', text: "Reaction: Negate target creature's ability", reaction: { on: 'any' }, play: [{ t: 'creature', suppress: true, dur: 'turn' }] },
  { id: 'wiz_spellshield', name: 'Spell Shield', arch: 'abjurer', set: 'Starter', rarity: 'starter', cost: 1, type: 'spell', text: "Target creature can't be targeted until end of turn", play: [{ t: 'creature', kw: ['nospell', 'noattack'], dur: 'turn' }] },
  { id: 'wiz_deny', name: 'Deny', arch: 'abjurer', set: 'Starter', rarity: 'starter', cost: 2, type: 'reaction', text: 'Reaction: Negate target spell', reaction: { on: 'spell' }, play: [{ negate: true }] },
  { id: 'wiz_redirectspell', name: 'Redirect', arch: 'abjurer', set: 'Starter', rarity: 'starter', cost: 2, type: 'reaction', text: 'Reaction: Change target of a single-target spell', reaction: { on: 'spell' }, manual: true },
  { id: 'wiz_wardingcircle', name: 'Warding Circle', arch: 'abjurer', set: 'Starter', rarity: 'starter', cost: 3, type: 'persistent', atk: 0, hp: 2, text: "Persistent. Up to 2 creatures can't be targeted by enemy spells", play: [{ t: 'friendly', n: 2, upTo: true, kw: ['nospell'], dur: 'perm' }] },
  { id: 'wiz_reflect', name: 'Reflect', arch: 'abjurer', set: 'Starter', rarity: 'starter', cost: 3, type: 'reaction', text: 'Reaction: Negate target spell and deal 2 damage to caster', reaction: { on: 'spell' }, play: [{ negate: true }, { t: 'casterFace', dmg: 2 }] },

  // ---- ABJURER: Mystic (Common) ----
  { id: 'wiz_foresight', name: 'Foresight', arch: 'abjurer', set: 'Mystic', rarity: 'common', cost: 1, type: 'spell', text: "Look at the top 3 cards of the DM's deck. Draw a card", play: [{ peek: { deck: 'dm', n: 3 } }, { draw: 1 }] },
  { id: 'wiz_mindward', name: 'Mind Ward', arch: 'abjurer', set: 'Mystic', rarity: 'common', cost: 1, type: 'spell', text: 'Target creature cannot be targeted by spells until end of turn', play: [{ t: 'creature', kw: ['nospell'], dur: 'turn' }] },
  { id: 'wiz_premonition', name: 'Premonition', arch: 'abjurer', set: 'Mystic', rarity: 'common', cost: 1, type: 'reaction', text: 'Reaction: When a friendly creature would take damage, reduce it by 2', reaction: { on: 'attack' }, play: [{ t: 'reactionSubject', shieldC: 2 }] },
  { id: 'wiz_clarity', name: 'Clarity', arch: 'abjurer', set: 'Mystic', rarity: 'common', cost: 1, type: 'spell', text: "Draw a card. Look at the top card of the DM's deck", play: [{ draw: 1 }, { peek: { deck: 'dm', n: 1 } }] },
  { id: 'wiz_mysticbarrier', name: 'Mystic Barrier', arch: 'abjurer', set: 'Mystic', rarity: 'common', cost: 2, type: 'spell', text: 'Give all friendly creatures Shield 1', play: [{ t: 'allFriendly', shieldC: 1 }] },
  { id: 'wiz_sixthsense', name: 'Sixth Sense', arch: 'abjurer', set: 'Mystic', rarity: 'common', cost: 1, type: 'reaction', text: 'Reaction: Negate target spell that targets a creature', reaction: { on: 'spell' }, play: [{ negate: true }] },
  { id: 'wiz_calmmind', name: 'Calm Mind', arch: 'abjurer', set: 'Mystic', rarity: 'common', cost: 1, type: 'spell', text: 'Remove all negative effects from target creature', play: [{ t: 'creature', cleanse: true }] },
  { id: 'wiz_aurareading', name: 'Aura Reading', arch: 'abjurer', set: 'Mystic', rarity: 'common', cost: 2, type: 'spell', text: "Look at the DM's hand", play: [{ peek: { hand: 'dm' } }] },
  { id: 'wiz_forewarn', name: 'Forewarn', arch: 'abjurer', set: 'Mystic', rarity: 'common', cost: 2, type: 'reaction', text: "Reaction: Negate target spell. Look at the top 2 cards of the DM's deck", reaction: { on: 'spell' }, play: [{ negate: true }, { peek: { deck: 'dm', n: 2 } }] },
  { id: 'wiz_prescience', name: 'Prescience', arch: 'abjurer', set: 'Mystic', rarity: 'common', cost: 3, type: 'spell', text: 'Until your next turn, all friendly creatures take 1 less damage from all sources', manual: true },

  // ---- ABJURER: Demonic (Uncommon) ----
  { id: 'wiz_darkward', name: 'Dark Ward', arch: 'abjurer', set: 'Demonic', rarity: 'uncommon', cost: 1, type: 'reaction', text: 'Reaction: Negate target spell. Lose 2 player HP', reaction: { on: 'spell' }, cost2: { loseHP: 2 }, play: [{ negate: true }] },
  { id: 'wiz_demonicpact', name: 'Demonic Pact', arch: 'abjurer', set: 'Demonic', rarity: 'uncommon', cost: 2, type: 'reaction', text: 'Reaction: Negate target spell. Discard a card. Draw 2 cards', reaction: { on: 'spell' }, cost2: { discard: 1 }, play: [{ negate: true }, { draw: 2 }] },
  { id: 'wiz_infernalshield', name: 'Infernal Shield', arch: 'abjurer', set: 'Demonic', rarity: 'uncommon', cost: 1, type: 'reaction', text: 'Reaction: Target creature takes no damage from this attack. Lose 1 player HP', reaction: { on: 'attack' }, cost2: { loseHP: 1 }, play: [{ t: 'reactionSubject', kw: ['immune'], dur: 'turn' }] },
  { id: 'wiz_hellfirecounter', name: 'Hellfire Counter', arch: 'abjurer', set: 'Demonic', rarity: 'uncommon', cost: 2, type: 'reaction', text: 'Reaction: Negate target spell. Deal 3 damage to the caster. Lose 2 player HP', reaction: { on: 'spell' }, cost2: { loseHP: 2 }, play: [{ negate: true }, { t: 'casterFace', dmg: 3 }] },
  { id: 'wiz_soulbargain', name: 'Soul Bargain', arch: 'abjurer', set: 'Demonic', rarity: 'uncommon', cost: 1, type: 'reaction', text: 'Sacrifice a creature. Reaction: Negate target spell', reaction: { on: 'spell' }, cost2: { sac: 1 }, play: [{ negate: true }] },
  { id: 'wiz_bloodseal', name: 'Blood Seal', arch: 'abjurer', set: 'Demonic', rarity: 'uncommon', cost: 2, type: 'reaction', text: "Reaction: Negate target creature's ability. That creature gets -2/-2 permanently. Lose 1 player HP", reaction: { on: 'any' }, cost2: { loseHP: 1 }, play: [{ t: 'creature', suppress: true, dur: 'turn', buffA: -2, buffH: -2 }] },
  { id: 'wiz_forbiddenknowledge', name: 'Forbidden Knowledge', arch: 'abjurer', set: 'Demonic', rarity: 'uncommon', cost: 2, type: 'reaction', text: 'Reaction: When DM draws cards, look at them. Choose one and discard it. Lose 2 player HP', reaction: { on: 'any' }, manual: true },
  { id: 'wiz_fiendsembrace', name: "Fiend's Embrace", arch: 'abjurer', set: 'Demonic', rarity: 'uncommon', cost: 3, type: 'spell', text: "Target creature cannot be destroyed until your next turn. At your next turn, lose player HP equal to the creature's mana cost", manual: true },
  { id: 'wiz_abyssalbanishment', name: 'Abyssal Banishment', arch: 'abjurer', set: 'Demonic', rarity: 'uncommon', cost: 3, type: 'reaction', text: 'Reaction: When DM plays a creature, exile it. Lose player HP equal to its mana cost', reaction: { on: 'creaturePlayed' }, manual: true },
  { id: 'wiz_bindingcontract', name: 'Binding Contract', arch: 'abjurer', set: 'Demonic', rarity: 'uncommon', cost: 2, type: 'persistent', atk: 0, hp: 2, text: 'Persistent. Once per DM turn, you may negate a spell by losing 3 player HP', manualNote: 'Use during DM turn: negate a spell, lose 3 player HP' },

  // ---- ABJURER: Holy (Uncommon) ----
  { id: 'wiz_blessedward', name: 'Blessed Ward', arch: 'abjurer', set: 'Holy', rarity: 'uncommon', cost: 1, type: 'reaction', text: 'Reaction: Reduce damage to target creature by 3', reaction: { on: 'attack' }, play: [{ t: 'reactionSubject', shieldC: 3 }] },
  { id: 'wiz_sanctify', name: 'Sanctify', arch: 'abjurer', set: 'Holy', rarity: 'uncommon', cost: 2, type: 'spell', text: 'Target creature cannot be targeted by DM spells until your next turn', play: [{ t: 'creature', kw: ['nospell'], dur: 1 }] },
  { id: 'wiz_holyground', name: 'Holy Ground', arch: 'abjurer', set: 'Holy', rarity: 'uncommon', cost: 3, type: 'persistent', atk: 0, hp: 3, text: 'Persistent. All friendly creatures take 1 less damage from all sources', manualNote: 'Damage reduction 1 while on board' },
  { id: 'wiz_purifyinglight', name: 'Purifying Light', arch: 'abjurer', set: 'Holy', rarity: 'uncommon', cost: 1, type: 'spell', text: 'Remove all negative effects from target creature. Restore 1 health', play: [{ t: 'creature', cleanse: true, healC: 1 }] },
  { id: 'wiz_sacredshield', name: 'Sacred Shield', arch: 'abjurer', set: 'Holy', rarity: 'uncommon', cost: 2, type: 'reaction', text: 'Reaction: Target creature gains Shield 4', reaction: { on: 'any' }, play: [{ t: 'creature', shieldC: 4 }] },
  { id: 'wiz_divineintervention', name: 'Divine Intervention', arch: 'abjurer', set: 'Holy', rarity: 'uncommon', cost: 3, type: 'reaction', text: 'Reaction: When a friendly creature would die, it survives with 1 health instead. It gains Shield 2', reaction: { on: 'wouldDie' }, play: [{ survive: 1, shieldAfter: 2 }] },
  { id: 'wiz_consecrate', name: 'Consecrate', arch: 'abjurer', set: 'Holy', rarity: 'uncommon', cost: 2, type: 'reaction', text: "Reaction: When DM plays a persistent or tower, return it to the DM's hand", reaction: { on: 'any' }, manual: true },
  { id: 'wiz_hallowedcircle', name: 'Hallowed Circle', arch: 'abjurer', set: 'Holy', rarity: 'uncommon', cost: 2, type: 'persistent', atk: 0, hp: 2, text: 'Persistent. Reaction: Once per DM turn, reduce damage to player HP by 3', manualNote: 'Once per DM turn: reduce player HP damage by 3' },
  { id: 'wiz_banishinglight', name: 'Banishing Light', arch: 'abjurer', set: 'Holy', rarity: 'uncommon', cost: 2, type: 'reaction', text: "Reaction: When DM plays a creature with cost 3 or less, return it to the DM's hand", reaction: { on: 'creaturePlayed' }, play: [{ bounce: { t: 'reactionSubject', costMax: 3 } }] },
  { id: 'wiz_absolution', name: 'Absolution', arch: 'abjurer', set: 'Holy', rarity: 'uncommon', cost: 3, type: 'spell', text: 'Restore 4 player HP. All friendly creatures gain Shield 1', play: [{ heal: 4 }, { t: 'allFriendly', shieldC: 1 }] },

  // ---- ABJURER: Divine (Rare) ----
  { id: 'wiz_divinerejection', name: 'Divine Rejection', arch: 'abjurer', set: 'Divine', rarity: 'rare', cost: 5, type: 'reaction', text: "Reaction: Negate target spell. The DM loses mana equal to that spell's cost", reaction: { on: 'spell' }, play: [{ negate: true, drainCasterMana: true }] },
  { id: 'wiz_smite', name: 'Smite', arch: 'abjurer', set: 'Divine', rarity: 'rare', cost: 5, type: 'reaction', text: 'Reaction: When an enemy creature attacks, destroy it if its attack is 4 or less', reaction: { on: 'attack' }, play: [{ destroyAttackerIfAtkMax: 4 }] },
  { id: 'wiz_heavenlyaegis', name: 'Heavenly Aegis', arch: 'abjurer', set: 'Divine', rarity: 'rare', cost: 6, type: 'spell', text: 'Target creature gains "cannot be destroyed" until your next turn', play: [{ t: 'creature', kw: ['indestructible'], dur: 1 }] },
  { id: 'wiz_wrath', name: 'Wrath', arch: 'abjurer', set: 'Divine', rarity: 'rare', cost: 7, type: 'reaction', text: 'Reaction: When player HP takes damage, deal that much damage to all enemy creatures', reaction: { on: 'any' }, manual: true },
  { id: 'wiz_sacredseal', name: 'Sacred Seal', arch: 'abjurer', set: 'Divine', rarity: 'rare', cost: 6, type: 'persistent', atk: 0, hp: 4, text: "Persistent. The DM's spells cost 1 more to play", manualNote: 'DM spells cost +1 while on board' },
  { id: 'wiz_judgment', name: 'Judgment', arch: 'abjurer', set: 'Divine', rarity: 'rare', cost: 6, type: 'reaction', text: 'Reaction: When DM plays a creature with cost 5+, deal 5 damage to it', reaction: { on: 'creaturePlayed' }, play: [{ t: 'reactionSubject', dmg: 5, costMin: 5 }] },
  { id: 'wiz_radiantshield', name: 'Radiant Shield', arch: 'abjurer', set: 'Divine', rarity: 'rare', cost: 5, type: 'reaction', text: 'Reaction: Negate all damage to player HP this attack. Deal 2 damage to the attacker', reaction: { on: 'attack' }, manual: true },
  { id: 'wiz_inviolable', name: 'Inviolable', arch: 'abjurer', set: 'Divine', rarity: 'rare', cost: 5, type: 'reaction', text: 'Reaction: Target creature cannot be targeted or damaged by anything until your next turn', reaction: { on: 'any' }, play: [{ t: 'creature', kw: ['immune', 'nospell', 'noattack'], dur: 1 }] },
  { id: 'wiz_divineauthority', name: 'Divine Authority', arch: 'abjurer', set: 'Divine', rarity: 'rare', cost: 7, type: 'persistent', atk: 0, hp: 3, text: "Persistent. Once per DM turn, you may negate a creature's ability without paying mana", manualNote: 'Once per DM turn: suppress a creature ability for free' },
  { id: 'wiz_covenant', name: 'Covenant', arch: 'abjurer', set: 'Divine', rarity: 'rare', cost: 6, type: 'reaction', text: 'Reaction: When a friendly persistent or tower would be destroyed, negate the destruction. Lose 2 player HP', reaction: { on: 'wouldDie' }, cost2: { loseHP: 2 }, play: [{ survive: 'full' }] },

  // ---- ABJURER: Eldritch/Outer (Legendary) ----
  { id: 'wiz_eldritchseal', name: 'Eldritch Seal', arch: 'abjurer', set: 'Eldritch', rarity: 'legendary', cost: 9, type: 'persistent', atk: 0, hp: 6, text: 'Persistent. Reaction: Exile target creature, persistent, or tower. Exile Eldritch Seal. Can only be used once', activated: { name: 'Exile target', once: true, actions: [{ t: 'any', exile: true, sacSelfExile: true }] } },
  { id: 'wiz_outergate', name: 'Outer Gate', arch: 'abjurer', set: 'Eldritch', rarity: 'legendary', cost: 8, type: 'reaction', text: "Reaction: At the start of the DM's turn, the DM cannot untap their mana this turn. Exile this card", reaction: { on: 'any' }, manual: true },
];
